-- Migration for allowances table
CREATE TABLE allowances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    value numeric(8,2) NOT NULL CHECK (value >= 0),
    value_type text NOT NULL DEFAULT 'percentage',
    designations_id bigint,
    employee_type text NOT NULL DEFAULT 'Teaching',
    wef date NOT NULL,
    end_date date,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (value_type IN ('flat','percentage')),
    CHECK (employee_type IN ('Teaching','Non-Teaching')),
    CHECK (status IN ('active','inactive'))
);
