CREATE TABLE IF NOT EXISTS associations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asso_name VARCHAR(255) NOT NULL,
  category VARCHAR(30) NOT NULL DEFAULT 'Associated',
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT associations_category_check CHECK (category IN ('Associated', 'Temporary associated', 'Disassociated')),
  CONSTRAINT associations_status_check CHECK (status IN ('active', 'inactive'))
);