CREATE TABLE IF NOT EXISTS designations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  design_name VARCHAR(255) NOT NULL,
  isadditional SMALLINT NOT NULL DEFAULT 0,
  isvacational VARCHAR(20) NOT NULL DEFAULT 'Vacational',
  leave_authorizer VARCHAR(20) NOT NULL DEFAULT 'HoD',
  emp_type VARCHAR(15) NOT NULL DEFAULT '0',
  status VARCHAR(10) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT designations_isvacational_check CHECK (isvacational IN ('Vacational', 'Non-Vacational')),
  CONSTRAINT designations_leave_authorizer_check CHECK (leave_authorizer IN ('Principal', 'HoD', 'Chairman'))
);