-- Migration for allowance_staff table
CREATE TABLE allowance_staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allowance_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    month varchar(255) NOT NULL,
    year integer NOT NULL,
    status text NOT NULL DEFAULT 'active',
    grade varchar(255),
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
