-- Migration for annual_increments table
CREATE TABLE annual_increments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    wef date NOT NULL,
    additional_days integer NOT NULL,
    additional_days_type text NOT NULL DEFAULT 'permanent',
    gc varchar(255) NOT NULL,
    reason varchar(255) NOT NULL DEFAULT 'null',
    basic bigint NOT NULL CHECK (basic >= 0),
    created_at timestamp,
    updated_at timestamp,
    CHECK (additional_days_type IN ('current_year','permanent'))
);
