CREATE TABLE IF NOT EXISTS leaves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  longname VARCHAR(255) NOT NULL,
  shortname VARCHAR(255) NOT NULL,
  max_entitlement INTEGER NULL,
  min_days NUMERIC(8,2) NOT NULL,
  max_days NUMERIC(8,2) NULL,
  vacation_type VARCHAR(20) NOT NULL,
  applicable_to VARCHAR(20) NOT NULL DEFAULT 'all',
  leave_wef DATE NOT NULL,
  leave_end_date DATE NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT leaves_vacation_type_check CHECK (vacation_type IN ('Vacational', 'Non-vacational')),
  CONSTRAINT leaves_applicable_to_check CHECK (applicable_to IN ('confirmed', 'all')),
  CONSTRAINT leaves_status_check CHECK (status IN ('active', 'inactive'))
);