-- Migration for associations table
CREATE TABLE associations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asso_name varchar(255) NOT NULL,
    category text NOT NULL DEFAULT 'Associated',
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (category IN ('Associated','Temporary associated','Disassociated')),
    CHECK (status IN ('active','inactive'))
);
