CREATE TABLE IF NOT EXISTS qualifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qual_name VARCHAR(255) NOT NULL,
  qual_shortname VARCHAR(15) NOT NULL,
  status VARCHAR(20) DEFAULT 'Active',
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT qualifications_status_check CHECK (status IN ('Active', 'Inactive'))
);