-- Migration for association_staff table
CREATE TABLE association_staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    association_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    start_date date NOT NULL,
    closing_date date,
    end_date date,
    reason varchar(255),
    gcr varchar(255),
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
