CREATE TABLE IF NOT EXISTS castecategories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caste_name VARCHAR(255) NOT NULL,
  religion_id BIGINT NOT NULL,
  subcastes_name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  category_no VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT castecategories_religion_fk FOREIGN KEY (religion_id) REFERENCES religions(id)
);