-- Migration for castecategories table
CREATE TABLE castecategories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caste_name varchar(255) NOT NULL,
    religion_id bigint NOT NULL,
    subcastes_name varchar(255) NOT NULL,
    category varchar(255) NOT NULL,
    category_no varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
