-- Migration for combine_leaves table
CREATE TABLE combine_leaves (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_id bigint NOT NULL,
    combined_id bigint NOT NULL,
    sandwitchable text NOT NULL,
    wef date NOT NULL,
    closing_wef date,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (sandwitchable IN ('Bothside','Oneside')),
    CHECK (status IN ('active','inactive'))
);
