CREATE TABLE IF NOT EXISTS departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dept_name VARCHAR(255) NOT NULL,
  dept_shortname VARCHAR(10) NOT NULL,
  yoe DATE NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  hod_user_id BIGINT NULL,
  CONSTRAINT departments_hod_user_fk FOREIGN KEY (hod_user_id) REFERENCES users(id)
);