-- Migration for conferences_attendee_staff table
CREATE TABLE conferences_attendee_staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    conferences_attendee_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
