CREATE TABLE IF NOT EXISTS staffremunerationheads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  remunerationhead_id BIGINT NOT NULL,
  date_of_disbursement DATE NULL,
  amount DOUBLE PRECISION NULL,
  financial_year VARCHAR(255) NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT staffremunerationheads_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id),
  CONSTRAINT staffremunerationheads_head_fk FOREIGN KEY (remunerationhead_id) REFERENCES remunerationheads(id)
);