-- Migration for conferences_conducted_staff table
CREATE TABLE conferences_conducted_staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    conferences_conducted_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
