CREATE TABLE IF NOT EXISTS combine_leaves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  leave_id BIGINT NOT NULL,
  combined_id BIGINT NOT NULL,
  sandwitchable VARCHAR(10) NOT NULL CHECK (sandwitchable IN ('Bothside', 'Oneside')),
  wef DATE NOT NULL,
  closing_wef DATE DEFAULT NULL,
  status VARCHAR(8) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT combine_leaves_leave_fk FOREIGN KEY (leave_id) REFERENCES leaves(id) ON DELETE CASCADE,
  CONSTRAINT combine_leaves_combined_fk FOREIGN KEY (combined_id) REFERENCES leaves(id) ON DELETE CASCADE
);
