-- Migration for consolidated_teaching_pays table
CREATE TABLE consolidated_teaching_pays (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    pay double precision NOT NULL CHECK (pay >= 0),
    start_date date NOT NULL,
    end_date date,
    reason varchar(255),
    gcr varchar(255) NOT NULL,
    closing_gcr varchar(255),
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
