CREATE TABLE IF NOT EXISTS ntpayscales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  payband VARCHAR(255) NOT NULL,
  wef DATE NOT NULL,
  closedon DATE DEFAULT NULL,
  status VARCHAR(8) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);
