-- Migration for consultancies table
CREATE TABLE consultancies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    egov_id varchar(30) NOT NULL,
    staff_id bigint NOT NULL,
    consultancy_title varchar(255) NOT NULL,
    agency varchar(1000) NOT NULL,
    from_date date NOT NULL,
    to_date date NOT NULL,
    amount double precision NOT NULL CHECK (amount >= 0),
    role text NOT NULL,
    consultancy_type text NOT NULL,
    validation_status text NOT NULL DEFAULT 'new',
    reason varchar(255),
    document varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (role IN ('Chief Coordinator','Coordinator','Team Member')),
    CHECK (consultancy_type IN ('consultancy','testing','','')),
    CHECK (validation_status IN ('new','valid','invalid','updated'))
);
