CREATE TABLE IF NOT EXISTS teaching_payscales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payscale_title VARCHAR(50) NOT NULL,
  basepay NUMERIC(8,2) NOT NULL,
  maxpay NUMERIC(8,2) NOT NULL,
  designations_id BIGINT NOT NULL,
  agp NUMERIC(8,2) NOT NULL,
  da NUMERIC(8,2) NOT NULL,
  hra NUMERIC(8,2) NOT NULL,
  cca NUMERIC(8,2) NOT NULL,
  wef DATE NOT NULL,
  closedon DATE DEFAULT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT teaching_payscales_designations_fk FOREIGN KEY (designations_id) REFERENCES designations(id) ON DELETE RESTRICT
);
