CREATE TABLE IF NOT EXISTS association_staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  association_id BIGINT NOT NULL,
  staff_id BIGINT NOT NULL,
  start_date DATE NOT NULL,
  closing_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  reason VARCHAR(255) DEFAULT NULL,
  gcr VARCHAR(255) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT association_staff_status_check CHECK (status IN ('active','inactive')),
  CONSTRAINT association_staff_association_fk FOREIGN KEY (association_id) REFERENCES associations(id) ON DELETE RESTRICT,
  CONSTRAINT association_staff_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE RESTRICT
);
