-- Migration for coordinators table
CREATE TABLE coordinators (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    employee_type text NOT NULL DEFAULT 'Teaching',
    created_at timestamp,
    updated_at timestamp,
    CHECK (employee_type IN ('Teaching','Non-Teaching','Both',''))
);
