CREATE TABLE IF NOT EXISTS department_staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id BIGINT NOT NULL,
  staff_id BIGINT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE DEFAULT NULL,
  reason VARCHAR(255) DEFAULT NULL,
  gcr VARCHAR(255) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT department_staff_status_check CHECK (status IN ('active','inactive','closed')),
  CONSTRAINT department_staff_department_fk FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE RESTRICT,
  CONSTRAINT department_staff_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE RESTRICT
);
