-- Migration for copyrights table
CREATE TABLE copyrights (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    egov_id varchar(50) NOT NULL,
    staff_id bigint NOT NULL,
    copyright_title varchar(255) NOT NULL,
    copyright_date date NOT NULL,
    author_name varchar(255) NOT NULL,
    status text NOT NULL,
    description varchar(255) NOT NULL,
    validation_status text NOT NULL DEFAULT 'new',
    reason varchar(255),
    document varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('Applied','Awarded')),
    CHECK (validation_status IN ('new','valid','invalid','updated'))
);
