-- Migration for course_student table
CREATE TABLE course_student (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL,
    student_id bigint NOT NULL,
    preference integer NOT NULL,
    final_preference varchar(255) NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('pending','rejected','enrolled','no vacancy'))
);
