CREATE TABLE IF NOT EXISTS employee_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  employee_type VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT employee_types_employee_type_check CHECK (employee_type IN ('Teaching','Non-Teaching')),
  CONSTRAINT employee_types_status_check CHECK (status IN ('active','inactive')),
  CONSTRAINT employee_types_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE RESTRICT
);
