-- Migration for daywise_admission_counts table
CREATE TABLE daywise_admission_counts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year varchar(255) NOT NULL,
    admission_count varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
