-- Migration for daywise__leaves table
CREATE TABLE daywise__leaves (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_staff_applications_id bigint NOT NULL,
    leave_id bigint NOT NULL,
    start date NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
