CREATE TABLE IF NOT EXISTS institution_staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution_id BIGINT NOT NULL,
  staff_id BIGINT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE DEFAULT NULL,
  reason VARCHAR(255) NOT NULL,
  gcr VARCHAR(255) DEFAULT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT institution_staff_status_check CHECK (status IN ('active','inactive')),
  CONSTRAINT institution_staff_institution_fk FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT,
  CONSTRAINT institution_staff_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE RESTRICT
);
