-- Migration for da_teaching_payscales table
CREATE TABLE da_teaching_payscales (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    da integer NOT NULL,
    teaching_payscale_id bigint NOT NULL,
    wef date NOT NULL,
    closed_date date,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
