-- Migration for departments table
CREATE TABLE departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name varchar(255) NOT NULL,
    dept_shortname varchar(10) NOT NULL,
    yoe date NOT NULL,
    status varchar(20) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    hod_user_id bigint
);
