CREATE TABLE IF NOT EXISTS leave_staff_entitlements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INTEGER NOT NULL,
  staff_id BIGINT NOT NULL,
  leave_id BIGINT NOT NULL,
  entitled_curr_year INTEGER NOT NULL DEFAULT 0,
  accumulated INTEGER DEFAULT 0,
  consumed_curr_year NUMERIC(6,1) NOT NULL DEFAULT 0.0,
  encashed_curr_year INTEGER DEFAULT 0,
  total_encashed INTEGER DEFAULT 0,
  wef DATE NOT NULL,
  remarks VARCHAR(500) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
  updated_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
  CONSTRAINT leave_staff_entitlements_status_check CHECK (status IN ('active','inactive')),
  CONSTRAINT leave_staff_entitlements_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE RESTRICT,
  CONSTRAINT leave_staff_entitlements_leave_fk FOREIGN KEY (leave_id) REFERENCES leaves(id) ON DELETE RESTRICT
);
