-- Migration for department_domains table
CREATE TABLE department_domains (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain varchar(255) NOT NULL,
    department_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
