CREATE TABLE IF NOT EXISTS ntpayscale_staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  ntpayscale_id BIGINT NOT NULL,
  level SMALLINT NOT NULL DEFAULT 1,
  start_date DATE NOT NULL,
  end_date DATE DEFAULT NULL,
  reason VARCHAR(255) DEFAULT NULL,
  gcr VARCHAR(255) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT ntpayscale_staff_status_check CHECK (status IN ('active','inactive')),
  CONSTRAINT ntpayscale_staff_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE RESTRICT,
  CONSTRAINT ntpayscale_staff_ntpayscale_fk FOREIGN KEY (ntpayscale_id) REFERENCES ntpayscales(id) ON DELETE RESTRICT
);
