-- Migration for department_event table
CREATE TABLE department_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL,
    department_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
