-- Migration for department_notice table
CREATE TABLE department_notice (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id bigint NOT NULL,
    department_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
