CREATE TABLE IF NOT EXISTS qualification_staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qualification_id BIGINT NOT NULL,
  staff_id BIGINT NOT NULL,
  board_university VARCHAR(255) NOT NULL,
  grade VARCHAR(64) DEFAULT NULL,
  yop DATE DEFAULT NULL,
  status VARCHAR(20) DEFAULT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT qualification_staff_status_check CHECK (status IN ('Persuing','Completed')),
  CONSTRAINT qualification_staff_qualification_fk FOREIGN KEY (qualification_id) REFERENCES qualifications(id) ON DELETE RESTRICT,
  CONSTRAINT qualification_staff_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE RESTRICT
);
