CREATE TABLE IF NOT EXISTS ntcpayscales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  basepay NUMERIC(12,2) NOT NULL,
  allowance INTEGER NOT NULL,
  year SMALLINT NOT NULL,
  wef DATE NOT NULL,
  gcr VARCHAR(255) NOT NULL,
  closedon DATE DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT ntcpayscales_status_check CHECK (status IN ('active','inactive'))
);
