-- Migration for dept_mgtquota_admissions table
CREATE TABLE dept_mgtquota_admissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id bigint NOT NULL,
    quota varchar(255) NOT NULL,
    status varchar(255),
    created_at timestamp,
    updated_at timestamp
);
