CREATE TABLE IF NOT EXISTS ntcpayscale_staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  ntcpayscale_id BIGINT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE DEFAULT NULL,
  reason VARCHAR(255) DEFAULT NULL,
  gcr VARCHAR(255) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,
  CONSTRAINT ntcpayscale_staff_status_check CHECK (status IN ('active','inactive')),
  CONSTRAINT ntcpayscale_staff_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE RESTRICT,
  CONSTRAINT ntcpayscale_staff_ntcpayscale_fk FOREIGN KEY (ntcpayscale_id) REFERENCES ntcpayscales(id) ON DELETE RESTRICT
);
