-- Migration for dept_stationary_indents table
CREATE TABLE dept_stationary_indents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id bigint NOT NULL,
    reason varchar(255),
    status varchar(64),
    created_at timestamp,
    updated_at timestamp
);
