-- Migration for designations table
CREATE TABLE designations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    design_name varchar(255) NOT NULL,
    isadditional smallint NOT NULL DEFAULT 0,
    isvacational text NOT NULL DEFAULT 'Vacational',
    leave_authorizer text NOT NULL DEFAULT 'HoD',
    emp_type varchar(15) NOT NULL DEFAULT '0',
    status varchar(10) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (isvacational IN ('Vacational','Non-Vacational')),
    CHECK (leave_authorizer IN ('Principal','HoD','Chairman'))
);
