-- Migration for designation_ntpayscale table
CREATE TABLE designation_ntpayscale (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation_id bigint NOT NULL,
    ntpayscale_id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date,
    reason varchar(255),
    gcr varchar(255),
    status varchar(15) NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp
);
