-- Migration for designation_staff table
CREATE TABLE designation_staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    designation_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    dept_id bigint,
    start_date date NOT NULL,
    end_date date,
    allowance_status text,
    reason varchar(255),
    gcr varchar(255),
    gcr_close varchar(255),
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (allowance_status IN ('Allowance','Grading','Both','') OR allowance_status IS NULL),
    CHECK (status IN ('active','inactive'))
);
