-- Migration for employee_types table
CREATE TABLE employee_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    employee_type text NOT NULL,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (employee_type IN ('Teaching','Non-Teaching')),
    CHECK (status IN ('active','inactive'))
);
