-- Migration for events table
CREATE TABLE events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    event_name varchar(255) NOT NULL,
    start_date timestamp NOT NULL,
    to_date timestamp NOT NULL,
    location varchar(255) NOT NULL,
    organizers varchar(255) NOT NULL,
    event_website varchar(255) NOT NULL,
    staff_type text NOT NULL,
    attachment text,
    created_at timestamp,
    updated_at timestamp,
    CHECK (staff_type IN ('Teaching','Non-Teaching','All'))
);
