-- Migration for ev_requests table
CREATE TABLE ev_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    usn varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    phone_no varchar(255) NOT NULL,
    batch varchar(255),
    program varchar(255) NOT NULL,
    cgpa_percentage varchar(255),
    company_name varchar(255),
    purpose varchar(255),
    passing_year varchar(255),
    degree_obtained varchar(255),
    document varchar(255),
    created_at timestamp,
    updated_at timestamp
);
