-- Migration for exam_section_issues table
CREATE TABLE exam_section_issues (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issues varchar(255) NOT NULL,
    remarks varchar(255) NOT NULL,
    category_name text NOT NULL DEFAULT 'regular',
    staff_id bigint NOT NULL,
    duration integer NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (category_name IN ('regular','unusual'))
);
