-- Migration for fastrack_courses table
CREATE TABLE fastrack_courses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code varchar(255) NOT NULL,
    course_name varchar(255) NOT NULL,
    department_id bigint,
    ft_course_type_id bigint,
    ft_instance_id bigint NOT NULL,
    no_of_students varchar(255),
    created_at timestamp,
    updated_at timestamp
);
