-- Migration for fastrack_expenses table
CREATE TABLE fastrack_expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ft_expense_master_id bigint NOT NULL,
    academic_year varchar(10) NOT NULL,
    expense_amount integer NOT NULL CHECK (expense_amount >= 0),
    created_at timestamp,
    updated_at timestamp
);
