-- Migration for fastrack_expenses_master table
CREATE TABLE fastrack_expenses_master (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
