-- Migration for fastrack_instances table
CREATE TABLE fastrack_instances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ft_instance_name varchar(255) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    academic_year varchar(255) NOT NULL,
    scheme_id bigint NOT NULL,
    max_theory_class varchar(255) NOT NULL,
    max_lab_class varchar(255) NOT NULL,
    total_fees_collected integer,
    deadline_date timestamp,
    created_at timestamp,
    updated_at timestamp
);
