-- Migration for fastrack_instance_program table
CREATE TABLE fastrack_instance_program (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fastrack_instance_id bigint NOT NULL,
    program_id bigint NOT NULL,
    semester integer,
    created_at timestamp,
    updated_at timestamp
);
