-- Migration for fastrack_pays table
CREATE TABLE fastrack_pays (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year varchar(255) NOT NULL,
    management integer,
    rem_theory integer,
    rem_lab_teaching integer,
    rem_lab_instructors integer,
    rem_lab_peon integer,
    created_at timestamp,
    updated_at timestamp
);
