-- Migration for fastrack_staffs table
CREATE TABLE fastrack_staffs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    instructor_foreman_id integer,
    peon_attender_id integer,
    course_id bigint NOT NULL,
    classes_conducted integer,
    labs_conducted integer,
    status text DEFAULT 'Pending',
    document varchar(255),
    ft_justification varchar(255),
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('Pending','Verified','Approved','') OR status IS NULL)
);
