-- Migration for festival_advances table
CREATE TABLE festival_advances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    fyear smallint NOT NULL CHECK (fyear BETWEEN 1900 AND 9999),
    amount bigint NOT NULL CHECK (amount >= 0),
    start_date date NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
