-- Migration for fixed_nt_pays table
CREATE TABLE fixed_nt_pays (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    pay double precision NOT NULL CHECK (pay >= 0),
    start_date date,
    end_date date,
    status text NOT NULL,
    reason varchar(255),
    gcr varchar(255) NOT NULL,
    closed_gcr varchar(255),
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
