-- Migration for ftcourses table
CREATE TABLE ftcourses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_type varchar(255) NOT NULL,
    is_remunerated text NOT NULL DEFAULT 'Yes',
    created_at timestamp,
    updated_at timestamp,
    CHECK (is_remunerated IN ('Yes','No','',''))
);
