-- Migration for general_achievements table
CREATE TABLE general_achievements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    award varchar(255) NOT NULL,
    year integer NOT NULL,
    details varchar(255) NOT NULL,
    awarding_body varchar(255),
    validation_status text NOT NULL DEFAULT 'new',
    reason varchar(225),
    document varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (validation_status IN ('new','valid','invalid','updated'))
);
