-- Migration for grading_staffs table
CREATE TABLE grading_staffs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    month varchar(255) NOT NULL,
    year integer NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'active',
    grade varchar(255),
    created_at timestamp,
    updated_at timestamp
);
