-- Migration for holidayrhs table
CREATE TABLE holidayrhs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year integer NOT NULL,
    title varchar(50) NOT NULL,
    start date NOT NULL,
    day varchar(255) NOT NULL,
    type text NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (type IN ('Holiday','RH'))
);
