-- Migration for industries table
CREATE TABLE industries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    location varchar(255) NOT NULL,
    staff_id bigint NOT NULL,
    department_id bigint NOT NULL,
    registration_no varchar(255),
    year_of_establishment varchar(255),
    created_at timestamp,
    updated_at timestamp
);
