-- Migration for industryintakes table
CREATE TABLE industryintakes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    industry_id bigint NOT NULL,
    academic_year varchar(255) NOT NULL,
    intake integer NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
