-- Migration for institutions table
CREATE TABLE institutions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    acronym varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
