-- Migration for institution_staff table
CREATE TABLE institution_staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date,
    reason varchar(255) NOT NULL,
    gcr varchar(255),
    status text NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
