-- Migration for interactions table
CREATE TABLE interactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    studentinternship_id bigint NOT NULL,
    spoc_id bigint NOT NULL,
    department_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    idate date NOT NULL,
    topic varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    file varchar(255),
    type varchar(255) NOT NULL,
    interaction_with varchar(255) NOT NULL,
    remark text,
    student_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
