-- Migration for issue_timelines table
CREATE TABLE issue_timelines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_of_interaction date NOT NULL,
    interaction varchar(255) NOT NULL,
    followup_date date,
    status text NOT NULL DEFAULT 'open',
    status_updated_date date NOT NULL,
    status_updated_by bigint NOT NULL,
    student_issue_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('open','followup','resolved'))
);
