-- Migration for laptoploans table
CREATE TABLE laptoploans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    date_of_application date NOT NULL,
    configuration varchar(255) NOT NULL,
    amount integer NOT NULL CHECK (amount >= 0),
    emi integer NOT NULL CHECK (emi >= 0),
    start_date date NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
