-- Migration for leads table
CREATE TABLE leads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    phone varchar(255),
    location varchar(255),
    candidate_email varchar(255),
    status text NOT NULL DEFAULT 'New',
    contact_date date,
    academic_year varchar(255),
    lead_staff_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('New','Interested','Hot Lead','Not Interested','Query','Invalid','Admitted to Other College','No Response','Number repeated'))
);
