-- Migration for lead_interactions table
CREATE TABLE lead_interactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id bigint NOT NULL,
    interaction_type text NOT NULL DEFAULT 'call',
    interaction_topic varchar(255) NOT NULL,
    notes text,
    interaction_date date,
    interaction_time time NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'New',
    staff_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (interaction_type IN ('call','email','meeting','other'))
);
