-- Migration for lead_program table
CREATE TABLE lead_program (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id bigint NOT NULL,
    program_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    preference varchar(11) DEFAULT 'I'
);
