-- Migration for leaves table
CREATE TABLE leaves (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    longname varchar(255) NOT NULL,
    shortname varchar(255) NOT NULL,
    max_entitlement integer,
    min_days numeric(8,2) NOT NULL,
    max_days numeric(8,2),
    vacation_type text NOT NULL,
    applicable_to text NOT NULL DEFAULT 'all',
    leave_wef date NOT NULL,
    leave_end_date date,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (vacation_type IN ('Vacational','Non-vacational')),
    CHECK (applicable_to IN ('confirmed','all')),
    CHECK (status IN ('active','inactive'))
);
