-- Migration for leave_staff_applications table
CREATE TABLE leave_staff_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_id bigint NOT NULL,
    cl_type text DEFAULT 'Full',
    staff_id bigint NOT NULL,
    alternate bigint NOT NULL,
    additional_alternate bigint,
    reason text NOT NULL,
    recommender bigint,
    approver bigint,
    start date NOT NULL,
    "end" date NOT NULL,
    no_of_days real NOT NULL,
    appl_status text NOT NULL DEFAULT 'pending',
    leave_status text NOT NULL DEFAULT 'awaiting',
    year smallint NOT NULL CHECK (year BETWEEN 1900 AND 9999),
    created_at timestamp,
    updated_at timestamp,
    CHECK (cl_type IN ('Morning','Afternoon','Full') OR cl_type IS NULL),
    CHECK (appl_status IN ('recommended','pending','rejected','approved','cancelled')),
    CHECK (leave_status IN ('taken','awaiting'))
);
