-- Migration for leave_staff_entitlements table
CREATE TABLE leave_staff_entitlements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year integer NOT NULL CHECK (year >= 0),
    staff_id bigint NOT NULL,
    leave_id bigint NOT NULL,
    entitled_curr_year smallint NOT NULL DEFAULT 0 CHECK (entitled_curr_year >= 0),
    accumulated integer DEFAULT 0 CHECK (accumulated >= 0),
    consumed_curr_year numeric(5,1) NOT NULL DEFAULT 0.0 CHECK (consumed_curr_year >= 0),
    encashed_curr_year integer DEFAULT 0 CHECK (encashed_curr_year >= 0),
    total_encashed integer DEFAULT 0 CHECK (total_encashed >= 0),
    wef date NOT NULL,
    remarks varchar(500),
    status text NOT NULL DEFAULT 'active',
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
    CHECK (status IN ('active','inactive'))
);
