-- Migration for mgmtmembers table
CREATE TABLE mgmtmembers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_name varchar(30) NOT NULL,
    designation varchar(30) NOT NULL DEFAULT 'member',
    level varchar(30) NOT NULL,
    status varchar(20) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
