-- Migration for naacs table
CREATE TABLE naacs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle varchar(255) NOT NULL,
    score varchar(255) NOT NULL,
    year_of_assesment varchar(255) NOT NULL,
    grade varchar(255) NOT NULL,
    v_from_date date NOT NULL,
    v_to_date date NOT NULL,
    status varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
