-- Migration for nbas table
CREATE TABLE nbas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle varchar(255),
    year_of_assesments varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
