-- Migration for nba_programs table
CREATE TABLE nba_programs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nba_id bigint NOT NULL,
    program_id bigint NOT NULL,
    v_from_date date NOT NULL,
    v_to_date date NOT NULL,
    score numeric(8,2) NOT NULL,
    exten_status text DEFAULT 'Not Extended',
    exten_period varchar(255),
    exten_form date,
    exten_to date,
    status varchar(255) DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (exten_status IN ('Extended','Not Extended') OR exten_status IS NULL)
);
