-- Migration for nirfs table
CREATE TABLE nirfs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year varchar(255) NOT NULL,
    rank_detail varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
