-- Migration for notices table
CREATE TABLE notices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    title varchar(255) NOT NULL,
    date date NOT NULL,
    description varchar(255) NOT NULL,
    staff_type text NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (staff_type IN ('Teaching','Non-Teaching','All'))
);
