-- Migration for notifications table
CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    notification_title varchar(255) NOT NULL,
    notification_type text NOT NULL,
    date date NOT NULL,
    description varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (notification_type IN ('Leave','Qualification','Event'))
);
