-- Migration for ntcpayscales table
CREATE TABLE ntcpayscales (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    basepay bigint NOT NULL,
    allowance integer NOT NULL,
    year smallint NOT NULL,
    wef date NOT NULL,
    gcr varchar(255) NOT NULL,
    closedon date,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
