-- Migration for ntpayscales table
CREATE TABLE ntpayscales (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    payband varchar(255) NOT NULL,
    wef date NOT NULL,
    closedon date,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
