-- Migration for ntpayscale_staff table
CREATE TABLE ntpayscale_staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    ntpayscale_id bigint NOT NULL,
    level smallint NOT NULL DEFAULT 1,
    start_date date NOT NULL,
    end_date date,
    reason varchar(255),
    gcr varchar(255),
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
