-- Migration for patents table
CREATE TABLE patents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    egov_id varchar(30) NOT NULL,
    staff_id bigint NOT NULL,
    appl_no varchar(255) NOT NULL,
    appl_date date NOT NULL,
    title varchar(255) NOT NULL,
    stream_domain varchar(255) NOT NULL,
    status text NOT NULL,
    patent_no varchar(255),
    publication_no varchar(255),
    publication_date date,
    validation_status text NOT NULL DEFAULT 'new',
    reason varchar(255),
    document varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('Pending','Awarded','Rejected','Granted','Published')),
    CHECK (validation_status IN ('new','valid','invalid','updated'))
);
