-- Migration for personal_access_tokens table
CREATE TABLE personal_access_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tokenable_type varchar(255) NOT NULL,
    tokenable_id bigint NOT NULL,
    name varchar(255) NOT NULL,
    token varchar(64) NOT NULL,
    abilities text,
    last_used_at timestamp,
    expires_at timestamp,
    created_at timestamp,
    updated_at timestamp
);
