-- Migration for post_tickets table
CREATE TABLE post_tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL,
    user_id bigint NOT NULL,
    title varchar(300) NOT NULL,
    description varchar(255) NOT NULL,
    post_attachment text,
    created_at timestamp,
    updated_at timestamp
);
