-- Migration for professional_activity_attendee_staff table
CREATE TABLE professional_activity_attendee_staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_activity_attendee_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
