-- Migration for professional_activity_conducted_staff table
CREATE TABLE professional_activity_conducted_staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professional_activity_conducted_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
