-- Migration for programs table
CREATE TABLE programs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_name varchar(255) NOT NULL,
    program_code varchar(255) NOT NULL,
    department_id bigint,
    start_date date NOT NULL,
    close_date date NOT NULL,
    type text NOT NULL,
    program_intake varchar(255),
    created_at timestamp,
    updated_at timestamp,
    CHECK (type IN ('UG','PG'))
);
