-- Migration for qualifications table
CREATE TABLE qualifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qual_name varchar(255) NOT NULL,
    qual_shortname varchar(15) NOT NULL,
    status text DEFAULT 'Active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('Active','Inactive') OR status IS NULL)
);
