-- Migration for qualification_staff table
CREATE TABLE qualification_staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qualification_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    board_university varchar(255) NOT NULL,
    grade varchar(64),
    yop date,
    status text,
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('Persuing','Completed') OR status IS NULL)
);
