-- Migration for religions table
CREATE TABLE religions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    religion_name varchar(30) NOT NULL,
    status varchar(20) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
