-- Migration for remunerationheads table
CREATE TABLE remunerationheads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remuneration_head varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
