-- Migration for reviewer_editors table
CREATE TABLE reviewer_editors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    egov_id varchar(50) NOT NULL,
    staff_id bigint NOT NULL,
    title varchar(255) NOT NULL,
    journal_name varchar(255) NOT NULL,
    publisher_name varchar(255) NOT NULL,
    reviewed_date date NOT NULL,
    level text NOT NULL,
    other_level varchar(255),
    category text NOT NULL,
    validation_status text NOT NULL DEFAULT 'new',
    reason varchar(255),
    document varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CHECK (level IN ('Q1','Q2','Q3','Q4','SCI','Web of Science','Scopus Indexed','UGC General','Other')),
    CHECK (category IN ('Journal','Conference Proceeding')),
    CHECK (validation_status IN ('new','valid','invalid','updated'))
);
