-- Migration for schemes table
CREATE TABLE schemes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheme_name varchar(255) NOT NULL,
    status varchar(255) NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp
);
