-- Migration for spocs table
CREATE TABLE spocs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    industry_id bigint NOT NULL,
    name varchar(255) NOT NULL,
    phone bigint NOT NULL,
    email varchar(255) NOT NULL,
    designation varchar(255) NOT NULL,
    department varchar(255),
    staff_id bigint NOT NULL,
    department_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
