-- Migration for stafflics table
CREATE TABLE stafflics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    policy_no integer NOT NULL,
    premium double precision NOT NULL CHECK (premium >= 0),
    start_date date NOT NULL,
    end_date date,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','transfered','stopped',''))
);
