-- Migration for stafflic_transactions table
CREATE TABLE stafflic_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stafflic_id bigint NOT NULL,
    gst numeric(10,0) NOT NULL CHECK (gst >= 0),
    month varchar(255) NOT NULL,
    year smallint NOT NULL CHECK (year BETWEEN 1900 AND 9999),
    dop date NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
