-- Migration for staffloans table
CREATE TABLE staffloans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    member_id varchar(255) NOT NULL,
    loan_type varchar(255) NOT NULL,
    loan_id varchar(255) NOT NULL,
    loan_amount numeric(8,2) NOT NULL CHECK (loan_amount >= 0),
    monthly_emi numeric(8,2) NOT NULL CHECK (monthly_emi >= 0),
    start_date date NOT NULL,
    end_date date,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
