-- Migration for staffremunerationheads table
CREATE TABLE staffremunerationheads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    remunerationhead_id bigint NOT NULL,
    date_of_disbursement date,
    amount double precision,
    financial_year varchar(255),
    created_at timestamp,
    updated_at timestamp
);
