-- Migration for staffshares table
CREATE TABLE staffshares (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    member_id varchar(20) NOT NULL,
    amount double precision,
    start_date date NOT NULL,
    end_date date,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive','',''))
);
