-- Migration for staff_form16s table
CREATE TABLE staff_form16s (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    document varchar(255) NOT NULL,
    partb varchar(255),
    year smallint NOT NULL CHECK (year BETWEEN 1900 AND 9999),
    created_at timestamp,
    updated_at timestamp
);
