-- Migration for staff_taxregime table
CREATE TABLE staff_taxregime (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    tax_heads_id bigint NOT NULL,
    finyear varchar(12) NOT NULL,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
