-- Migration for staff_tds table
CREATE TABLE staff_tds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    staffsalary_id bigint NOT NULL,
    staff_taxregime_id bigint NOT NULL,
    staff_tdshead_id bigint NOT NULL,
    tds double precision NOT NULL CHECK (tds >= 0),
    month varchar(255) NOT NULL,
    year smallint NOT NULL CHECK (year BETWEEN 1900 AND 9999),
    created_at timestamp,
    updated_at timestamp
);
