-- Migration for staff_teaching_payscale table
CREATE TABLE staff_teaching_payscale (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    teaching_payscale_id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date,
    reason varchar(255),
    gcr varchar(255),
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
