-- Migration for stationary_indent_and_grants table
CREATE TABLE stationary_indent_and_grants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stationary_id bigint NOT NULL,
    request_quantity varchar(255) NOT NULL,
    request_date date NOT NULL,
    given_quantity varchar(255),
    grant_quantity varchar(255) NOT NULL DEFAULT '0',
    grant_date date,
    dept_stationary_indent_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
