-- Migration for stationaries table
CREATE TABLE stationaries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    specification varchar(255) NOT NULL,
    quantity integer NOT NULL CHECK (quantity >= 0),
    created_at timestamp,
    updated_at timestamp
);
