-- Migration for studentinternships table
CREATE TABLE studentinternships (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    years varchar(255),
    sdate varchar(255) NOT NULL,
    edate varchar(255) NOT NULL,
    industry_id bigint NOT NULL,
    spoc_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    department_id bigint NOT NULL,
    stipend integer,
    created_at timestamp,
    updated_at timestamp
);
