-- Migration for students table
CREATE TABLE students (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usn varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    batch varchar(255) NOT NULL,
    email varchar(255),
    contact_no varchar(255),
    no_of_weeks varchar(255) NOT NULL,
    internal_mark integer,
    external_mark integer,
    department_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
