-- Migration for student_issues table
CREATE TABLE student_issues (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usn varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    phone_no bigint NOT NULL,
    exam_section_issue_id bigint,
    other_issue varchar(255),
    description varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
