-- Migration for student_studentinternship table
CREATE TABLE student_studentinternship (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    studentinternship_id bigint NOT NULL,
    department_id bigint NOT NULL,
    staff_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
