-- Migration for tax_heads table
CREATE TABLE tax_heads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    year smallint NOT NULL CHECK (year BETWEEN 1900 AND 9999),
    std_ded numeric(10,2) NOT NULL DEFAULT 75000.00,
    threshold integer NOT NULL,
    margin integer NOT NULL,
    status text NOT NULL DEFAULT 'Active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('Active','Inactive'))
);
