-- Migration for tds_heads table
CREATE TABLE tds_heads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    status text NOT NULL DEFAULT 'Active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('Active','Inactive'))
);
