-- Migration for teaching_payscale table
CREATE TABLE teaching_payscale (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    pay_level varchar(255) NOT NULL,
    pay_band varchar(255) NOT NULL,
    grade_pay varchar(255),
    pay_matrix varchar(255),
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
