-- Migration for user_roles table
CREATE TABLE user_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
