-- Migration for user_tokens table
CREATE TABLE user_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    token varchar(255) NOT NULL,
    type varchar(50) NOT NULL,
    expires_at timestamp,
    created_at timestamp,
    updated_at timestamp
);
