-- Migration for work_experience table
CREATE TABLE work_experience (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    organization varchar(255) NOT NULL,
    designation varchar(255) NOT NULL,
    from_date date NOT NULL,
    to_date date,
    experience_years integer,
    created_at timestamp,
    updated_at timestamp
);
