-- Migration for yearwise_staff_salary table
CREATE TABLE yearwise_staff_salary (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id bigint NOT NULL,
    year smallint NOT NULL CHECK (year BETWEEN 1900 AND 9999),
    gross_salary numeric(12,2) NOT NULL,
    net_salary numeric(12,2) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);
