-- Migration for z_users table
CREATE TABLE z_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    email varchar(255),
    phone varchar(20),
    status text NOT NULL DEFAULT 'active',
    created_at timestamp,
    updated_at timestamp,
    CHECK (status IN ('active','inactive'))
);
