-- coordinator_staffs was imported without its auto-increment: id had no default, no sequence
-- and no primary key. Every insert from the HOD coordinator staff page failed with
-- "null value in column id violates not-null constraint".
-- Turns id into an identity primary key and starts it past the highest existing id.
-- Safe to run more than once.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'coordinator_staffs' AND column_name = 'id' AND is_identity = 'YES'
  ) THEN
    ALTER TABLE coordinator_staffs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'coordinator_staffs'::regclass AND contype = 'p'
  ) THEN
    ALTER TABLE coordinator_staffs ADD PRIMARY KEY (id);
  END IF;
END $$;

SELECT setval(
  pg_get_serial_sequence('coordinator_staffs', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 0) FROM coordinator_staffs), 1),
  (SELECT COUNT(*) > 0 FROM coordinator_staffs)
);
