CREATE SCHEMA IF NOT EXISTS gitoffice;
SET search_path = gitoffice;

CREATE TABLE admissions (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
student_name varchar(255) NOT NULL,
program_id bigint NOT NULL,
program_type varchar(255),
mobile_no varchar(255),
status varchar(255) NOT NULL,
batch varchar(255) NOT NULL,
fees varchar(255),
admission_date date,
remarks varchar(255),
email varchar(255),
pan_card varchar(255),
qual_exam varchar(255),
qual_exam_percentage varchar(255),
entrance_exam varchar(255),
fees_received varchar(255),
balance_due_date date,
member_id bigint,
wl_no integer,
enquiry_date date,
cancel_date date,
place varchar(255),
hostel varchar(255) NOT NULL,
mobile_no_2 varchar(255),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE allowances (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title varchar(255) NOT NULL,
value numeric(8,2) NOT NULL CHECK (value >= 0),
value_type text NOT NULL DEFAULT 'percentage',
designations_id bigint,
employee_type text NOT NULL DEFAULT 'Teaching',
wef date NOT NULL,
end_date date,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (value_type IN ('flat','percentage')),
CHECK (employee_type IN ('Teaching','Non-Teaching')),
CHECK (status IN ('active','inactive'))
);

CREATE TABLE allowance_staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
allowance_id bigint NOT NULL,
staff_id bigint NOT NULL,
month varchar(255) NOT NULL,
year integer NOT NULL,
status text NOT NULL DEFAULT 'active',
grade varchar(255),
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE annual_increments (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
wef date NOT NULL,
additional_days integer NOT NULL,
additional_days_type text NOT NULL DEFAULT 'permanent',
gc varchar(255) NOT NULL,
reason varchar(255) NOT NULL DEFAULT 'null',
basic bigint NOT NULL CHECK (basic >= 0),
created_at timestamp,
updated_at timestamp,
CHECK (additional_days_type IN ('current_year','permanent'))
);

CREATE TABLE associate_professor_applications (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
advertisement_instance date,
application_no varchar(255),
applicant_name varchar(150) NOT NULL,
email varchar(255) NOT NULL,
applicant_address varchar(255),
applicant_phone bigint,
phd_university varchar(255),
phd_reputed_university boolean,
ug_class text,
ug_branches varchar(255),
pg_class text,
pg_specialization varchar(255),
ug_pg_remarks varchar(255),
experience_years varchar(255),
experience_teaching varchar(255),
experience_research varchar(255),
experience_industry varchar(255),
experience_remarks varchar(255),
phd_date date,
post_phd_experience varchar(255),
phd_remarks varchar(255),
research_papers_count integer,
papers_in_sci integer,
papers_in_ugc integer,
papers_in_aicte integer,
research_remarks varchar(255),
eligibility_status text,
remarks text,
publication varchar(255),
date_of_birth date,
caste_name varchar(255),
department_id bigint,
created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
CHECK (ug_class IN ('F','S','T') OR ug_class IS NULL),
CHECK (pg_class IN ('F','S','T') OR pg_class IS NULL),
CHECK (eligibility_status IN ('Eligible','Not Eligible') OR eligibility_status IS NULL)
);

CREATE TABLE associations (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
asso_name varchar(255) NOT NULL,
category text NOT NULL DEFAULT 'Associated',
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (category IN ('Associated','Temporary associated','Disassociated')),
CHECK (status IN ('active','inactive'))
);

CREATE TABLE association_staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
association_id bigint NOT NULL,
staff_id bigint NOT NULL,
start_date date NOT NULL,
closing_date date,
end_date date,
reason varchar(255),
gcr varchar(255),
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE autonomous_allowances (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
department_id bigint NOT NULL,
subject1_classes_conducted integer,
subject1_max_classes integer,
subject1_percentage numeric(5,2),
subject2_classes_conducted integer,
subject2_max_classes integer,
subject2_percentage numeric(5,2),
subject3_classes_conducted integer,
subject3_max_classes integer,
subject3_percentage numeric(5,2),
average_percentage numeric(5,2),
feedback_percentage numeric(5,2),
feedback_marks numeric(8,2),
industry_activity_points integer,
checkbox_selections jsonb,
research_points integer,
grants_points integer,
dept_points integer,
organized_points integer,
hod_discretion integer,
principal_discretion integer,
total_marks integer,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE book_publications (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
egov_id varchar(30),
staff_id bigint NOT NULL,
title varchar(255) NOT NULL,
book_level text NOT NULL,
publisher_name varchar(255) NOT NULL,
edition varchar(255) NOT NULL,
doi varchar(255) NOT NULL,
date date NOT NULL,
issue varchar(255),
type text NOT NULL,
chapter_title varchar(255),
start_page_no integer,
end_page_no integer,
validation_status text NOT NULL DEFAULT 'new',
reason varchar(255),
document varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (book_level IN ('National','International')),
CHECK (type IN ('Book','Chapter')),
CHECK (validation_status IN ('new','valid','invalid','updated'))
);

CREATE TABLE castecategories (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
caste_name varchar(255) NOT NULL,
religion_id bigint NOT NULL,
subcastes_name varchar(255) NOT NULL,
category varchar(255) NOT NULL,
category_no varchar(255) NOT NULL,
status varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE combine_leaves (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
leave_id bigint NOT NULL,
combined_id bigint NOT NULL,
sandwitchable text NOT NULL,
wef date NOT NULL,
closing_wef date,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (sandwitchable IN ('Bothside','Oneside')),
CHECK (status IN ('active','inactive'))
);

CREATE TABLE conferences_attendees (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
egov_id varchar(30) NOT NULL,
conference_name varchar(255) NOT NULL,
attended_as text NOT NULL,
from_date date NOT NULL,
to_date date NOT NULL,
no_of_days varchar(255) NOT NULL,
title varchar(255) NOT NULL,
place varchar(255) NOT NULL,
sponsored text,
sponsored_by varchar(255),
amount integer,
weblink varchar(255),
type_of_level text NOT NULL,
issn_no varchar(255),
validation_status text NOT NULL DEFAULT 'new',
reason varchar(225),
document varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (attended_as IN ('Resource Person','Participant','Paper Presenter','Session Chair')),
CHECK (sponsored IN ('Yes','No') OR sponsored IS NULL),
CHECK (type_of_level IN ('National','International')),
CHECK (validation_status IN ('new','valid','invalid','updated'))
);

CREATE TABLE conferences_attendee_staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
conferences_attendee_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE conferences_conducteds (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
egov_id varchar(30) NOT NULL,
conference_name varchar(255) NOT NULL,
co_organizer varchar(255),
no_of_participants varchar(255) NOT NULL,
sponsored text,
sponsoring_agency varchar(255),
from_date date NOT NULL,
to_date date NOT NULL,
no_of_days integer NOT NULL,
place varchar(255) NOT NULL,
publisher varchar(255) NOT NULL,
role text NOT NULL,
weblink varchar(255),
type_of_level text NOT NULL,
issn_no varchar(255),
validation_status text NOT NULL DEFAULT 'new',
reason varchar(255),
document varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (sponsored IN ('Yes','No') OR sponsored IS NULL),
CHECK (role IN ('Convener','Co-convener','Team Member','Coordinator')),
CHECK (type_of_level IN ('National','International')),
CHECK (validation_status IN ('new','valid','invalid','updated'))
);

CREATE TABLE conferences_conducted_staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
conferences_conducted_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE consolidated_teaching_pays (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
pay double precision NOT NULL CHECK (pay >= 0),
start_date date NOT NULL,
end_date date,
reason varchar(255),
gcr varchar(255) NOT NULL,
closing_gcr varchar(255),
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE consultancies (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
egov_id varchar(30) NOT NULL,
staff_id bigint NOT NULL,
consultancy_title varchar(255) NOT NULL,
agency varchar(1000) NOT NULL,
from_date date NOT NULL,
to_date date NOT NULL,
amount double precision NOT NULL CHECK (amount >= 0),
role text NOT NULL,
consultancy_type text NOT NULL,
validation_status text NOT NULL DEFAULT 'new',
reason varchar(255),
document varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (role IN ('Chief Coordinator','Coordinator','Team Member')),
CHECK (consultancy_type IN ('consultancy','testing','','')),
CHECK (validation_status IN ('new','valid','invalid','updated'))
);

CREATE TABLE coordinators (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
employee_type text NOT NULL DEFAULT 'Teaching',
created_at timestamp,
updated_at timestamp,
CHECK (employee_type IN ('Teaching','Non-Teaching','Both',''))
);

CREATE TABLE copyrights (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
egov_id varchar(50) NOT NULL,
staff_id bigint NOT NULL,
copyright_title varchar(255) NOT NULL,
copyright_date date NOT NULL,
author_name varchar(255) NOT NULL,
status text NOT NULL,
description varchar(255) NOT NULL,
validation_status text NOT NULL DEFAULT 'new',
reason varchar(255),
document varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('Applied','Awarded')),
CHECK (validation_status IN ('new','valid','invalid','updated'))
);

CREATE TABLE course_student (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
course_id bigint NOT NULL,
student_id bigint NOT NULL,
preference integer NOT NULL,
final_preference varchar(255) NOT NULL,
status text NOT NULL DEFAULT 'pending',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('pending','rejected','enrolled','no vacancy'))
);

CREATE TABLE daywise_admission_counts (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
academic_year varchar(255) NOT NULL,
admission_count varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE daywise__leaves (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
leave_staff_applications_id bigint NOT NULL,
leave_id bigint NOT NULL,
start date NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE da_teaching_payscales (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
da integer NOT NULL,
teaching_payscale_id bigint NOT NULL,
wef date NOT NULL,
closed_date date,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE departments (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
dept_name varchar(255) NOT NULL,
dept_shortname varchar(10) NOT NULL,
yoe date NOT NULL,
status varchar(20) NOT NULL,
created_at timestamp,
updated_at timestamp,
hod_user_id bigint
);

CREATE TABLE department_domains (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
domain varchar(255) NOT NULL,
department_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE department_event (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
event_id bigint NOT NULL,
department_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE department_notice (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
notice_id bigint NOT NULL,
department_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE department_staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
department_id bigint NOT NULL,
staff_id bigint NOT NULL,
start_date date NOT NULL,
end_date date,
reason varchar(255),
gcr varchar(255),
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive','closed'))
);

CREATE TABLE dept_mgtquota_admissions (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
program_id bigint NOT NULL,
quota varchar(255) NOT NULL,
status varchar(255),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE dept_stationary_indents (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
department_id bigint NOT NULL,
reason varchar(255),
status varchar(64),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE designations (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
design_name varchar(255) NOT NULL,
isadditional smallint NOT NULL DEFAULT 0,
isvacational text NOT NULL DEFAULT 'Vacational',
leave_authorizer text NOT NULL DEFAULT 'HoD',
emp_type varchar(15) NOT NULL DEFAULT '0',
status varchar(10) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (isvacational IN ('Vacational','Non-Vacational')),
CHECK (leave_authorizer IN ('Principal','HoD','Chairman'))
);

CREATE TABLE designation_ntcpayscale (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
designation_id bigint NOT NULL,
ntcpayscale_id bigint NOT NULL,
start_date date NOT NULL,
end_date date,
reason varchar(255),
gcr varchar(255),
status varchar(15) NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp
);

CREATE TABLE designation_ntpayscale (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
designation_id bigint NOT NULL,
ntpayscale_id bigint NOT NULL,
start_date date NOT NULL,
end_date date,
reason varchar(255),
gcr varchar(255),
status varchar(15) NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp
);

CREATE TABLE designation_staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
designation_id bigint NOT NULL,
staff_id bigint NOT NULL,
dept_id bigint,
start_date date NOT NULL,
end_date date,
allowance_status text,
reason varchar(255),
gcr varchar(255),
gcr_close varchar(255),
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (allowance_status IN ('Allowance','Grading','Both','') OR allowance_status IS NULL),
CHECK (status IN ('active','inactive'))
);

CREATE TABLE employee_types (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
employee_type text NOT NULL,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (employee_type IN ('Teaching','Non-Teaching')),
CHECK (status IN ('active','inactive'))
);

CREATE TABLE events (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id bigint NOT NULL,
event_name varchar(255) NOT NULL,
start_date timestamp NOT NULL,
to_date timestamp NOT NULL,
location varchar(255) NOT NULL,
organizers varchar(255) NOT NULL,
event_website varchar(255) NOT NULL,
staff_type text NOT NULL,
attachment text,
created_at timestamp,
updated_at timestamp,
CHECK (staff_type IN ('Teaching','Non-Teaching','All'))
);

CREATE TABLE ev_requests (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
usn varchar(255) NOT NULL,
email varchar(255) NOT NULL,
phone_no varchar(255) NOT NULL,
batch varchar(255),
program varchar(255) NOT NULL,
cgpa_percentage varchar(255),
company_name varchar(255),
purpose varchar(255),
passing_year varchar(255),
degree_obtained varchar(255),
document varchar(255),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE exam_section_issues (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
issues varchar(255) NOT NULL,
remarks varchar(255) NOT NULL,
category_name text NOT NULL DEFAULT 'regular',
staff_id bigint NOT NULL,
duration integer NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (category_name IN ('regular','unusual'))
);

CREATE TABLE failed_jobs (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
uuid varchar(255) NOT NULL,
connection text NOT NULL,
queue text NOT NULL,
payload text NOT NULL,
exception text NOT NULL,
failed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fastrack_courses (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
course_code varchar(255) NOT NULL,
course_name varchar(255) NOT NULL,
department_id bigint,
ft_course_type_id bigint,
ft_instance_id bigint NOT NULL,
no_of_students varchar(255),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE fastrack_expenses (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
ft_expense_master_id bigint NOT NULL,
academic_year varchar(10) NOT NULL,
expense_amount integer NOT NULL CHECK (expense_amount >= 0),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE fastrack_expenses_master (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE fastrack_instances (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
ft_instance_name varchar(255) NOT NULL,
start_date date NOT NULL,
end_date date NOT NULL,
academic_year varchar(255) NOT NULL,
scheme_id bigint NOT NULL,
max_theory_class varchar(255) NOT NULL,
max_lab_class varchar(255) NOT NULL,
total_fees_collected integer,
deadline_date timestamp,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE fastrack_instance_program (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
fastrack_instance_id bigint NOT NULL,
program_id bigint NOT NULL,
semester integer,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE fastrack_pays (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
academic_year varchar(255) NOT NULL,
management integer,
rem_theory integer,
rem_lab_teaching integer,
rem_lab_instructors integer,
rem_lab_peon integer,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE fastrack_staffs (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
instructor_foreman_id integer,
peon_attender_id integer,
course_id bigint NOT NULL,
classes_conducted integer,
labs_conducted integer,
status text DEFAULT 'Pending',
document varchar(255),
ft_justification varchar(255),
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('Pending','Verified','Approved','') OR status IS NULL)
);

CREATE TABLE festival_advances (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
fyear smallint NOT NULL CHECK (fyear BETWEEN 1900 AND 9999),
amount bigint NOT NULL CHECK (amount >= 0),
start_date date NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE fixed_nt_pays (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
pay double precision NOT NULL CHECK (pay >= 0),
start_date date,
end_date date,
status text NOT NULL,
reason varchar(255),
gcr varchar(255) NOT NULL,
closed_gcr varchar(255),
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE ftcourses (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
course_type varchar(255) NOT NULL,
is_remunerated text NOT NULL DEFAULT 'Yes',
created_at timestamp,
updated_at timestamp,
CHECK (is_remunerated IN ('Yes','No','',''))
);

CREATE TABLE funded_projects (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
egov_id varchar(30) NOT NULL,
staff_id bigint NOT NULL,
proposal_title varchar(255) NOT NULL,
role text NOT NULL,
type text NOT NULL,
amount double precision NOT NULL CHECK (amount >= 0),
proposal_status text NOT NULL,
application_date date NOT NULL,
fund_received double precision CHECK (fund_received >= 0),
project_status text,
completion_year smallint CHECK (completion_year BETWEEN 1900 AND 9999),
validation_status text NOT NULL DEFAULT 'new',
reason varchar(255),
document varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (role IN ('Principle Investigator','Co-Investigator','Not-Applicable','Architect')),
CHECK (type IN ('Govt-funded','Private funded')),
CHECK (proposal_status IN ('Accepted','Pending','Rejected')),
CHECK (project_status IN ('On-Going','Completed') OR project_status IS NULL),
CHECK (validation_status IN ('new','valid','invalid','updated'))
);

CREATE TABLE general_achievements (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
award varchar(255) NOT NULL,
year integer NOT NULL,
details varchar(255) NOT NULL,
awarding_body varchar(255),
validation_status text NOT NULL DEFAULT 'new',
reason varchar(225),
document varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (validation_status IN ('new','valid','invalid','updated'))
);

CREATE TABLE grading_staffs (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
month varchar(255) NOT NULL,
year integer NOT NULL,
status varchar(255) NOT NULL DEFAULT 'active',
grade varchar(255),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE holidayrhs (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
year integer NOT NULL,
title varchar(50) NOT NULL,
start date NOT NULL,
day varchar(255) NOT NULL,
type text NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (type IN ('Holiday','RH'))
);

CREATE TABLE industries (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
location varchar(255) NOT NULL,
staff_id bigint NOT NULL,
department_id bigint NOT NULL,
registration_no varchar(255),
year_of_establishment varchar(255),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE industryintakes (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
industry_id bigint NOT NULL,
academic_year varchar(255) NOT NULL,
intake integer NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE institutions (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
acronym varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE institution_staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
institution_id bigint NOT NULL,
staff_id bigint NOT NULL,
start_date date NOT NULL,
end_date date,
reason varchar(255) NOT NULL,
gcr varchar(255),
status text NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE interactions (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
studentinternship_id bigint NOT NULL,
spoc_id bigint NOT NULL,
department_id bigint NOT NULL,
staff_id bigint NOT NULL,
idate date NOT NULL,
topic varchar(255) NOT NULL,
description varchar(255) NOT NULL,
file varchar(255),
type varchar(255) NOT NULL,
interaction_with varchar(255) NOT NULL,
remark text,
student_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE issue_timelines (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
date_of_interaction date NOT NULL,
interaction varchar(255) NOT NULL,
followup_date date,
status text NOT NULL DEFAULT 'open',
status_updated_date date NOT NULL,
status_updated_by bigint NOT NULL,
student_issue_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('open','followup','resolved'))
);

CREATE TABLE laptoploans (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
date_of_application date NOT NULL,
configuration varchar(255) NOT NULL,
amount integer NOT NULL CHECK (amount >= 0),
emi integer NOT NULL CHECK (emi >= 0),
start_date date NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE leads (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
phone varchar(255),
location varchar(255),
candidate_email varchar(255),
status text NOT NULL DEFAULT 'New',
contact_date date,
academic_year varchar(255),
lead_staff_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('New','Interested','Hot Lead','Not Interested','Query','Invalid','Admitted to Other College','No Response','Number repeated'))
);

CREATE TABLE lead_interactions (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
lead_id bigint NOT NULL,
interaction_type text NOT NULL DEFAULT 'call',
interaction_topic varchar(255) NOT NULL,
notes text,
interaction_date date,
interaction_time time NOT NULL,
status varchar(255) NOT NULL DEFAULT 'New',
staff_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (interaction_type IN ('call','email','meeting','other'))
);

CREATE TABLE lead_program (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
lead_id bigint NOT NULL,
program_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp,
preference varchar(11) DEFAULT 'I'
);

CREATE TABLE leaves (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
longname varchar(255) NOT NULL,
shortname varchar(255) NOT NULL,
max_entitlement integer,
min_days numeric(8,2) NOT NULL,
max_days numeric(8,2),
vacation_type text NOT NULL,
applicable_to text NOT NULL DEFAULT 'all',
leave_wef date NOT NULL,
leave_end_date date,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (vacation_type IN ('Vacational','Non-vacational')),
CHECK (applicable_to IN ('confirmed','all')),
CHECK (status IN ('active','inactive'))
);

CREATE TABLE leave_rules (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
leave_id bigint NOT NULL,
carry_forwardable text NOT NULL DEFAULT 'No',
cf_gcr varchar(255),
cf_wef date NOT NULL,
cf_closing_date date,
cf_closing_gcr varchar(255),
max_cf integer NOT NULL DEFAULT 0,
entitlement_post_max_cf integer,
encashable text NOT NULL DEFAULT 'No',
enc_gcr varchar(255),
enc_wef date NOT NULL,
enc_closing_date date,
enc_closing_gcr varchar(255),
max_enc integer NOT NULL DEFAULT 0,
gap text NOT NULL DEFAULT 'No',
gap_gcr varchar(255),
gap_wef date,
gap_closing_date date,
gap_closing_gcr varchar(255),
min_gap integer NOT NULL DEFAULT 0,
max_time_allowed integer,
period varchar(100),
prior_intimation_days integer DEFAULT 0,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (carry_forwardable IN ('Yes','No')),
CHECK (encashable IN ('Yes','No')),
CHECK (gap IN ('Yes','No')),
CHECK (status IN ('active','inactive'))
);

CREATE TABLE leave_staff_applications (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
leave_id bigint NOT NULL,
cl_type text DEFAULT 'Full',
staff_id bigint NOT NULL,
alternate bigint NOT NULL,
additional_alternate bigint,
reason text NOT NULL,
recommender bigint,
approver bigint,
start date NOT NULL,
"end" date NOT NULL,
no_of_days real NOT NULL,
appl_status text NOT NULL DEFAULT 'pending',
leave_status text NOT NULL DEFAULT 'awaiting',
year smallint NOT NULL CHECK (year BETWEEN 1900 AND 9999),
created_at timestamp,
updated_at timestamp,
CHECK (cl_type IN ('Morning','Afternoon','Full') OR cl_type IS NULL),
CHECK (appl_status IN ('recommended','pending','rejected','approved','cancelled')),
CHECK (leave_status IN ('taken','awaiting'))
);

CREATE TABLE leave_staff_entitlements (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
year integer NOT NULL CHECK (year >= 0),
staff_id bigint NOT NULL,
leave_id bigint NOT NULL,
entitled_curr_year smallint NOT NULL DEFAULT 0 CHECK (entitled_curr_year >= 0),
accumulated integer DEFAULT 0 CHECK (accumulated >= 0),
consumed_curr_year numeric(5,1) NOT NULL DEFAULT 0.0 CHECK (consumed_curr_year >= 0),
encashed_curr_year integer DEFAULT 0 CHECK (encashed_curr_year >= 0),
total_encashed integer DEFAULT 0 CHECK (total_encashed >= 0),
wef date NOT NULL,
remarks varchar(500),
status text NOT NULL DEFAULT 'active',
created_at timestamp DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE mgmtmembers (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
member_name varchar(30) NOT NULL,
designation varchar(30) NOT NULL DEFAULT 'member',
level varchar(30) NOT NULL,
status varchar(20) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE migrations (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
migration varchar(255) NOT NULL,
batch integer NOT NULL
);

CREATE TABLE naacs (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
cycle varchar(255) NOT NULL,
score varchar(255) NOT NULL,
year_of_assesment varchar(255) NOT NULL,
grade varchar(255) NOT NULL,
v_from_date date NOT NULL,
v_to_date date NOT NULL,
status varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE nbas (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
cycle varchar(255),
year_of_assesments varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE nba_programs (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nba_id bigint NOT NULL,
program_id bigint NOT NULL,
v_from_date date NOT NULL,
v_to_date date NOT NULL,
score numeric(8,2) NOT NULL,
exten_status text DEFAULT 'Not Extended',
exten_period varchar(255),
exten_form date,
exten_to date,
status varchar(255) DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (exten_status IN ('Extended','Not Extended') OR exten_status IS NULL)
);

CREATE TABLE nirfs (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
year varchar(255) NOT NULL,
rank_detail varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE notices (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id bigint NOT NULL,
title varchar(255) NOT NULL,
date date NOT NULL,
description varchar(255) NOT NULL,
staff_type text NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (staff_type IN ('Teaching','Non-Teaching','All'))
);

CREATE TABLE notifications (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id bigint NOT NULL,
notification_title varchar(255) NOT NULL,
notification_type text NOT NULL,
date date NOT NULL,
description varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (notification_type IN ('Leave','Qualification','Event'))
);

CREATE TABLE ntcpayscales (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
basepay bigint NOT NULL,
allowance integer NOT NULL,
year smallint NOT NULL,
wef date NOT NULL,
gcr varchar(255) NOT NULL,
closedon date,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE ntcpayscale_staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
ntcpayscale_id bigint NOT NULL,
start_date date NOT NULL,
end_date date,
reason varchar(255),
gcr varchar(255),
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE ntissue_timelines (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
date_of_interaction date NOT NULL,
interaction varchar(255) NOT NULL,
followup_date date NOT NULL,
status text NOT NULL DEFAULT 'open',
status_updated_date date NOT NULL,
status_updated_by bigint NOT NULL,
student_issue_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('open','followup','resolved'))
);

CREATE TABLE ntpayscales (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title varchar(255) NOT NULL,
payband varchar(255) NOT NULL,
wef date NOT NULL,
closedon date,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE ntpayscale_staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
ntpayscale_id bigint NOT NULL,
level smallint NOT NULL DEFAULT 1,
start_date date NOT NULL,
end_date date,
reason varchar(255),
gcr varchar(255),
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE password_reset_tokens (
email varchar(255) PRIMARY KEY,
token varchar(255) NOT NULL,
created_at timestamp
);

CREATE TABLE patents (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
egov_id varchar(30) NOT NULL,
staff_id bigint NOT NULL,
appl_no varchar(255) NOT NULL,
appl_date date NOT NULL,
title varchar(255) NOT NULL,
stream_domain varchar(255) NOT NULL,
status text NOT NULL,
patent_no varchar(255),
publication_no varchar(255),
publication_date date,
validation_status text NOT NULL DEFAULT 'new',
reason varchar(255),
document varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('Pending','Awarded','Rejected','Granted','Published')),
CHECK (validation_status IN ('new','valid','invalid','updated'))
);

CREATE TABLE personal_access_tokens (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
tokenable_type varchar(255) NOT NULL,
tokenable_id bigint NOT NULL,
name varchar(255) NOT NULL,
token varchar(64) NOT NULL,
abilities text,
last_used_at timestamp,
expires_at timestamp,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE post_tickets (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
ticket_id bigint NOT NULL,
user_id bigint NOT NULL,
title varchar(300) NOT NULL,
description varchar(255) NOT NULL,
post_attachment text,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE professional_activity_attendees (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
egov_id varchar(30) NOT NULL,
title varchar(255) NOT NULL,
organizer varchar(255) NOT NULL,
role text NOT NULL DEFAULT 'Participant',
level text NOT NULL,
category text NOT NULL,
sponsored text,
sponsored_by varchar(255),
from_date date NOT NULL,
to_date date NOT NULL,
no_of_days integer NOT NULL,
validation_status text NOT NULL DEFAULT 'new',
reason varchar(255),
document varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (role IN ('Participant','Resource Person','Jury')),
CHECK (level IN ('Local','National','International')),
CHECK (category IN ('Workshop','FDP','Seminar','Webinar','Certification Program','MDP/EDP','Hackathon','Space-Talk','Site Visit','STTP')),
CHECK (sponsored IN ('Yes','No') OR sponsored IS NULL),
CHECK (validation_status IN ('new','valid','invalid','updated'))
);

CREATE TABLE professional_activity_attendee_staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
professional_activity_attendee_id bigint NOT NULL,
staff_id bigint NOT NULL,
created_at timestamp DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE professional_activity_conducteds (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
egov_id varchar(50) NOT NULL,
title varchar(255) NOT NULL,
organizer varchar(255) NOT NULL,
co_organizer varchar(255),
level text NOT NULL,
category text NOT NULL,
sponsored text,
sponsoring_agency_name_address varchar(255),
from_date date NOT NULL,
to_date date NOT NULL,
place varchar(255) NOT NULL,
no_of_days varchar(255) NOT NULL,
role text,
validation_status text NOT NULL DEFAULT 'new',
reason varchar(255),
document varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (level IN ('Local','National','International')),
CHECK (category IN ('Workshop','Seminar','Webinar','FDP','STTP','MDP/EDP','Certification Program','Space-Talk','Site Visit','Hackathon')),
CHECK (sponsored IN ('Yes','No') OR sponsored IS NULL),
CHECK (role IN ('Coordinator','Convenor','Member','') OR role IS NULL),
CHECK (validation_status IN ('new','valid','invalid','updated'))
);

CREATE TABLE professional_activity_conducted_staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
professional_activity_conducted_id bigint NOT NULL,
staff_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE professor_applications (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
advertisement_instance date,
application_no varchar(255),
applicant_name varchar(150) NOT NULL,
email varchar(255) NOT NULL,
applicant_address varchar(255),
applicant_phone bigint,
phd_university varchar(255),
phd_reputed_university boolean,
ug_class text,
ug_branches varchar(255),
pg_class text,
pg_specialization varchar(255),
ug_pg_remarks varchar(255),
type text,
designation text,
industry_designation varchar(255),
from_date_asso_prof date,
to_date_asso_prof date,
experience_teaching varchar(255),
experience_research varchar(255),
experience_industry varchar(255),
experience_years varchar(255),
experience_remarks varchar(255),
post_asso_prof_experience varchar(255),
asso_prof_experience_remarks varchar(255),
associate_level varchar(255),
research_papers_count integer,
papers_in_sci integer,
papers_in_ugc integer,
papers_in_aicte integer,
research_scholars_count integer,
research_remarks varchar(255),
remarks varchar(255),
publication varchar(255),
date_of_birth date,
caste_name varchar(255) NOT NULL,
eligibility_status text,
department_id bigint NOT NULL,
created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
CHECK (ug_class IN ('F','S','T') OR ug_class IS NULL),
CHECK (pg_class IN ('F','S','T') OR pg_class IS NULL),
CHECK (type IN ('Education','Industry','','') OR type IS NULL),
CHECK (designation IN ('Assistant Professor','Associate Professor','Professor','') OR designation IS NULL),
CHECK (eligibility_status IN ('Eligible','Not Eligible') OR eligibility_status IS NULL)
);

CREATE TABLE programs (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
program_name varchar(255) NOT NULL,
program_code varchar(255) NOT NULL,
department_id bigint,
start_date date NOT NULL,
close_date date NOT NULL,
type text NOT NULL,
program_intake varchar(255),
created_at timestamp,
updated_at timestamp,
CHECK (type IN ('UG','PG'))
);

CREATE TABLE publications (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
egov_id varchar(30) NOT NULL,
staff_id bigint NOT NULL,
level text NOT NULL,
other_level varchar(255),
title varchar(255) NOT NULL,
date date NOT NULL,
journal varchar(255) NOT NULL,
doi_number varchar(255),
link varchar(255),
role varchar(255) NOT NULL,
volume varchar(255),
issue varchar(255),
page_no varchar(255),
year varchar(255) NOT NULL,
publication_type text NOT NULL,
validation_status text NOT NULL DEFAULT 'new',
reason varchar(255),
document varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (level IN ('Q1','Q2','Q3','Q4','Web of Science','SCI','Scopus Indexed','UGC General','Other')),
CHECK (publication_type IN ('Journal','Conference Proceeding')),
CHECK (validation_status IN ('new','valid','invalid','updated'))
);

CREATE TABLE qualifications (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
qual_name varchar(255) NOT NULL,
qual_shortname varchar(15) NOT NULL,
status text DEFAULT 'Active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('Active','Inactive') OR status IS NULL)
);

CREATE TABLE qualification_staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
qualification_id bigint NOT NULL,
staff_id bigint NOT NULL,
board_university varchar(255) NOT NULL,
grade varchar(64),
yop date,
status text,
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('Persuing','Completed') OR status IS NULL)
);

CREATE TABLE religions (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
religion_name varchar(30) NOT NULL,
status varchar(20) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE remunerationheads (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
remuneration_head varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE reviewer_editors (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
egov_id varchar(50) NOT NULL,
staff_id bigint NOT NULL,
title varchar(255) NOT NULL,
journal_name varchar(255) NOT NULL,
publisher_name varchar(255) NOT NULL,
reviewed_date date NOT NULL,
level text NOT NULL,
other_level varchar(255),
category text NOT NULL,
validation_status text NOT NULL DEFAULT 'new',
reason varchar(255),
document varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (level IN ('Q1','Q2','Q3','Q4','SCI','Web of Science','Scopus Indexed','UGC General','Other')),
CHECK (category IN ('Journal','Conference Proceeding')),
CHECK (validation_status IN ('new','valid','invalid','updated'))
);

CREATE TABLE schemes (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
scheme_name varchar(255) NOT NULL,
status varchar(255) NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp
);

CREATE TABLE spocs (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
industry_id bigint NOT NULL,
name varchar(255) NOT NULL,
phone bigint NOT NULL,
email varchar(255) NOT NULL,
designation varchar(255) NOT NULL,
department varchar(255),
staff_id bigint NOT NULL,
department_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE staff (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id bigint NOT NULL,
fname varchar(30) NOT NULL,
mname varchar(30),
lname varchar(30) NOT NULL,
local_address text NOT NULL,
permanent_address text NOT NULL,
dob date NOT NULL,
doj date NOT NULL,
religion_id bigint NOT NULL,
castecategory_id bigint NOT NULL,
gender text NOT NULL,
date_of_increment date,
date_of_superanuation date NOT NULL,
date_of_confirmation date,
bloodgroup varchar(5),
pan_card varchar(20),
adhar_card varchar(20),
contactno bigint,
aicte_id varchar(30),
vtu_id varchar(30),
esi_no varchar(30),
un_no varchar(30),
emergency_no numeric(21,0),
emergency_name varchar(30),
employeecode integer NOT NULL DEFAULT 0,
profile_photo varchar(255),
created_at timestamp,
updated_at timestamp,
pf varchar(100),
CHECK (gender IN ('female','male','others'))
);

CREATE TABLE stafflics (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
policy_no integer NOT NULL,
premium double precision NOT NULL CHECK (premium >= 0),
start_date date NOT NULL,
end_date date,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','transfered','stopped',''))
);

CREATE TABLE stafflic_transactions (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
stafflic_id bigint NOT NULL,
gst numeric(10,0) NOT NULL CHECK (gst >= 0),
month varchar(255) NOT NULL,
year smallint NOT NULL CHECK (year BETWEEN 1900 AND 9999),
dop date NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE staffloans (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
member_id varchar(255) NOT NULL,
loan_type varchar(255) NOT NULL,
loan_id varchar(255) NOT NULL,
loan_amount numeric(8,2) NOT NULL CHECK (loan_amount >= 0),
monthly_emi numeric(8,2) NOT NULL CHECK (monthly_emi >= 0),
start_date date NOT NULL,
end_date date,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE staffremunerationheads (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
remunerationhead_id bigint NOT NULL,
date_of_disbursement date,
amount double precision,
financial_year varchar(255),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE staffsalaries (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
rate bigint NOT NULL,
staff_id bigint NOT NULL,
basic numeric(8,2) NOT NULL CHECK (basic >= 0),
da numeric(8,2) NOT NULL CHECK (da >= 0),
hra numeric(8,2) NOT NULL CHECK (hra >= 0),
cca numeric(8,2) NOT NULL CHECK (cca >= 0),
special_incen numeric(8,2) NOT NULL CHECK (special_incen >= 0),
salary_arrears numeric(8,2) NOT NULL CHECK (salary_arrears >= 0),
special_allowances numeric(8,2) NOT NULL CHECK (special_allowances >= 0),
allowance_value numeric(8,2) NOT NULL CHECK (allowance_value >= 0),
gross_salary numeric(8,2) NOT NULL CHECK (gross_salary >= 0),
pf_deduction numeric(8,2) NOT NULL CHECK (pf_deduction >= 0),
pf_arrears numeric(8,2) NOT NULL CHECK (pf_arrears >= 0),
income_tax numeric(8,2) NOT NULL CHECK (income_tax >= 0),
prof_tax numeric(8,2) NOT NULL CHECK (prof_tax >= 0),
lic numeric(8,2) CHECK (lic >= 0),
gsli numeric(8,2) NOT NULL CHECK (gsli >= 0),
credit_shares numeric(8,2) NOT NULL CHECK (credit_shares >= 0),
credit_loan numeric(8,2) NOT NULL CHECK (credit_loan >= 0),
vidyaganapati numeric(8,2) NOT NULL CHECK (vidyaganapati >= 0),
forward_charges numeric(8,2) NOT NULL CHECK (forward_charges >= 0),
salary_recovery numeric(8,2) NOT NULL CHECK (salary_recovery >= 0),
ir numeric(8,2) NOT NULL CHECK (ir >= 0),
hra_recovery numeric(8,2) NOT NULL CHECK (hra_recovery >= 0),
laptop_computer numeric(8,2) NOT NULL CHECK (laptop_computer >= 0),
total_deductions numeric(8,2) NOT NULL CHECK (total_deductions >= 0),
net_salary numeric(8,2) NOT NULL CHECK (net_salary >= 0),
remarks varchar(625) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE staffshares (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
member_id varchar(20) NOT NULL,
amount double precision,
start_date date NOT NULL,
end_date date,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive','',''))
);

CREATE TABLE staff_form16s (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
document varchar(255) NOT NULL,
partb varchar(255),
year smallint NOT NULL CHECK (year BETWEEN 1900 AND 9999),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE staff_taxregime (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
tax_heads_id bigint NOT NULL,
finyear varchar(12) NOT NULL,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE staff_tds (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
staffsalary_id bigint NOT NULL,
staff_taxregime_id bigint NOT NULL,
staff_tdshead_id bigint NOT NULL,
tds double precision NOT NULL CHECK (tds >= 0),
month varchar(255) NOT NULL,
year smallint NOT NULL CHECK (year BETWEEN 1900 AND 9999),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE staff_teaching_payscale (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
staff_id bigint NOT NULL,
teaching_payscale_id bigint NOT NULL,
start_date date NOT NULL,
end_date date,
reason varchar(255),
gcr varchar(255),
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive'))
);

CREATE TABLE stationaries (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
specification varchar(255) NOT NULL,
quantity integer NOT NULL CHECK (quantity >= 0),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE stationary_indent_and_grants (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
stationary_id bigint NOT NULL,
request_quantity varchar(255) NOT NULL,
request_date date NOT NULL,
given_quantity varchar(255),
grant_quantity varchar(255) NOT NULL DEFAULT '0',
grant_date date,
dept_stationary_indent_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE studentinternships (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title varchar(255) NOT NULL,
years varchar(255),
sdate varchar(255) NOT NULL,
edate varchar(255) NOT NULL,
industry_id bigint NOT NULL,
spoc_id bigint NOT NULL,
staff_id bigint NOT NULL,
department_id bigint NOT NULL,
stipend integer,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE students (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
usn varchar(255) NOT NULL,
name varchar(255) NOT NULL,
batch varchar(255) NOT NULL,
email varchar(255),
contact_no varchar(255),
no_of_weeks varchar(255) NOT NULL,
internal_mark integer,
external_mark integer,
department_id bigint NOT NULL,
staff_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE student_issues (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
usn varchar(255) NOT NULL,
email varchar(255) NOT NULL,
phone_no bigint NOT NULL,
exam_section_issue_id bigint,
other_issue varchar(255),
description varchar(255) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE student_studentinternship (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
student_id bigint NOT NULL,
studentinternship_id bigint NOT NULL,
department_id bigint NOT NULL,
staff_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE tax_heads (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
year smallint NOT NULL CHECK (year BETWEEN 1900 AND 9999),
std_ded numeric(10,2) NOT NULL DEFAULT 75000.00,
threshold integer NOT NULL,
margin integer NOT NULL,
status text NOT NULL DEFAULT 'Active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('Active','Inactive'))
);

CREATE TABLE tax_slabs (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
regime_id bigint NOT NULL,
lower_limit numeric(10,2) NOT NULL,
upper_limit numeric(10,2),
tax_rate numeric(5,2) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE tdsheads (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
category varchar(50) NOT NULL,
description text,
status varchar(20) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE teaching_payscales (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
payscale_title varchar(50) NOT NULL,
basepay numeric(8,2) NOT NULL,
maxpay numeric(8,2) NOT NULL,
designations_id bigint NOT NULL,
agp numeric(8,2) NOT NULL,
da numeric(8,2) NOT NULL,
hra numeric(8,2) NOT NULL,
cca numeric(8,2) NOT NULL,
wef date NOT NULL,
closedon date,
status varchar(20) NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE tenders (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title varchar(255) NOT NULL,
start_date date NOT NULL,
close_date date NOT NULL,
user_id bigint NOT NULL,
status text NOT NULL DEFAULT 'active',
document varchar(255),
kls_institution varchar(255),
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','closed','inactive',''))
);

CREATE TABLE tender_configs (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
configuration text NOT NULL,
tender_id bigint NOT NULL,
unit varchar(255),
quantity integer NOT NULL CHECK (quantity >= 0),
remarks varchar(255),
term_conditions text,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE tender_config_vendors (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
tender_configs_id bigint NOT NULL,
t_vendor_id bigint NOT NULL,
rate numeric(10,2),
gst varchar(255),
vendor_remarks varchar(255),
warranty_period varchar(255),
vendor_terms_conditions text,
tender_status text NOT NULL DEFAULT 'Not Opened',
created_at timestamp,
updated_at timestamp,
CHECK (tender_status IN ('Opened','Not Opened','',''))
);

CREATE TABLE tender_departments (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
tender_id bigint NOT NULL,
department_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE tender_quote_otp (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
tender_id bigint NOT NULL,
t_vendor_id bigint NOT NULL,
otp varchar(255) NOT NULL,
expires_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE tender_t_vendor (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
tender_id bigint NOT NULL,
t_vendor_id bigint NOT NULL,
delivery_period date,
link_status text,
created_at timestamp DEFAULT CURRENT_TIMESTAMP,
updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
CHECK (link_status IN ('ACCEPTED','REJECTED','','') OR link_status IS NULL)
);

CREATE TABLE tickets (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title varchar(300) NOT NULL,
description text NOT NULL,
status text NOT NULL DEFAULT 'New',
attachment text,
user_id bigint NOT NULL,
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('New','Pending','Resolved'))
);

CREATE TABLE t_vendors (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar(255) NOT NULL,
propritor_name varchar(255) NOT NULL,
phone_no bigint NOT NULL,
gst_no varchar(255) NOT NULL,
address varchar(255) NOT NULL,
section varchar(255) NOT NULL,
status text NOT NULL DEFAULT 'active',
created_at timestamp,
updated_at timestamp,
CHECK (status IN ('active','inactive','',''))
);

CREATE TABLE users (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar(255) NOT NULL,
email_verified_at timestamp,
password varchar(255) NOT NULL,
role varchar(255) NOT NULL DEFAULT 'student',
status varchar(255) NOT NULL DEFAULT 'Active',
remember_token varchar(100),
session_id varchar(255),
created_at timestamp,
updated_at timestamp
);

CREATE TABLE vendors (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
address varchar(255) NOT NULL,
gst varchar(255),
contact_no bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE TABLE domains (
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255) NOT NULL,
department bigint NOT NULL,
created_at timestamp,
updated_at timestamp
);

CREATE UNIQUE INDEX book_publications_egov_id_uq ON book_publications (egov_id);
CREATE UNIQUE INDEX conferences_attendees_egov_id_uq ON conferences_attendees (egov_id);
CREATE UNIQUE INDEX conferences_conducteds_egov_id_uq ON conferences_conducteds (egov_id);
CREATE UNIQUE INDEX coordinators_name_uq ON coordinators (name);
CREATE UNIQUE INDEX failed_jobs_uuid_uq ON failed_jobs (uuid);
CREATE UNIQUE INDEX patents_egov_id_uq ON patents (egov_id);
CREATE UNIQUE INDEX personal_access_tokens_token_uq ON personal_access_tokens (token);
CREATE UNIQUE INDEX professional_activity_attendees_egov_id_uq ON professional_activity_attendees (egov_id);
CREATE UNIQUE INDEX users_email_uq ON users (email);
CREATE UNIQUE INDEX departments_dept_shortname_uq ON departments (dept_shortname);
CREATE UNIQUE INDEX designations_design_name_uq ON designations (design_name);

CREATE INDEX admissions_program_id_idx ON admissions (program_id);
CREATE INDEX admissions_member_id_idx ON admissions (member_id);
CREATE INDEX annual_increments_staff_id_idx ON annual_increments (staff_id);
CREATE INDEX association_staff_association_id_idx ON association_staff (association_id);
CREATE INDEX association_staff_staff_id_idx ON association_staff (staff_id);
CREATE INDEX autonomous_allowances_staff_id_idx ON autonomous_allowances (staff_id);
CREATE INDEX autonomous_allowances_department_id_idx ON autonomous_allowances (department_id);
CREATE INDEX book_publications_staff_id_idx ON book_publications (staff_id);
CREATE INDEX castecategories_religion_id_idx ON castecategories (religion_id);
CREATE INDEX combine_leaves_leave_id_idx ON combine_leaves (leave_id);
CREATE INDEX combine_leaves_combined_id_idx ON combine_leaves (combined_id);
CREATE INDEX conferences_attendee_staff_staff_id_idx ON conferences_attendee_staff (staff_id);
CREATE INDEX conferences_attendee_staff_conference_id_idx ON conferences_attendee_staff (conferences_attendee_id);
CREATE INDEX conferences_conducted_staff_staff_id_idx ON conferences_conducted_staff (staff_id);
CREATE INDEX conferences_conducted_staff_conference_id_idx ON conferences_conducted_staff (conferences_conducted_id);
CREATE INDEX consolidated_teaching_pays_staff_id_idx ON consolidated_teaching_pays (staff_id);
CREATE INDEX consultancies_staff_id_idx ON consultancies (staff_id);
CREATE INDEX copyrights_staff_id_idx ON copyrights (staff_id);
CREATE INDEX daywise_leaves_leave_staff_applications_id_idx ON daywise__leaves (leave_staff_applications_id);
CREATE INDEX departments_hod_user_id_idx ON departments (hod_user_id);
CREATE INDEX department_domains_department_id_idx ON department_domains (department_id);
CREATE INDEX department_event_event_id_idx ON department_event (event_id);
CREATE INDEX department_event_department_id_idx ON department_event (department_id);
CREATE INDEX department_notice_notice_id_idx ON department_notice (notice_id);
CREATE INDEX department_notice_department_id_idx ON department_notice (department_id);
CREATE INDEX department_staff_department_id_idx ON department_staff (department_id);
CREATE INDEX department_staff_staff_id_idx ON department_staff (staff_id);
CREATE INDEX dept_mgtquota_admissions_program_id_idx ON dept_mgtquota_admissions (program_id);
CREATE INDEX dept_stationary_indents_department_id_idx ON dept_stationary_indents (department_id);
CREATE INDEX designation_ntpayscale_designation_id_idx ON designation_ntpayscale (designation_id);
CREATE INDEX designation_ntpayscale_ntpayscale_id_idx ON designation_ntpayscale (ntpayscale_id);
CREATE INDEX designation_staff_designation_id_idx ON designation_staff (designation_id);
CREATE INDEX designation_staff_staff_id_idx ON designation_staff (staff_id);
CREATE INDEX employee_types_staff_id_idx ON employee_types (staff_id);
CREATE INDEX events_user_id_idx ON events (user_id);
CREATE INDEX fastrack_courses_department_id_idx ON fastrack_courses (department_id);
CREATE INDEX fastrack_courses_ft_course_type_id_idx ON fastrack_courses (ft_course_type_id);
CREATE INDEX fastrack_courses_ft_instance_id_idx ON fastrack_courses (ft_instance_id);
CREATE INDEX fastrack_expenses_ft_expense_master_id_idx ON fastrack_expenses (ft_expense_master_id);
CREATE INDEX fastrack_instances_scheme_id_idx ON fastrack_instances (scheme_id);
CREATE INDEX fastrack_instance_program_instance_id_idx ON fastrack_instance_program (fastrack_instance_id);
CREATE INDEX fastrack_instance_program_program_id_idx ON fastrack_instance_program (program_id);
CREATE INDEX fastrack_staffs_staff_id_idx ON fastrack_staffs (staff_id);
CREATE INDEX fastrack_staffs_course_id_idx ON fastrack_staffs (course_id);
CREATE INDEX fixed_nt_pays_staff_id_idx ON fixed_nt_pays (staff_id);
CREATE INDEX funded_projects_staff_id_idx ON funded_projects (staff_id);
CREATE INDEX general_achievements_staff_id_idx ON general_achievements (staff_id);
CREATE INDEX grading_staffs_staff_id_idx ON grading_staffs (staff_id);
CREATE INDEX industryintakes_industry_id_idx ON industryintakes (industry_id);
CREATE INDEX institution_staff_institution_id_idx ON institution_staff (institution_id);
CREATE INDEX institution_staff_staff_id_idx ON institution_staff (staff_id);
CREATE INDEX laptoploans_staff_id_idx ON laptoploans (staff_id);
CREATE INDEX lead_interactions_lead_id_idx ON lead_interactions (lead_id);
CREATE INDEX lead_interactions_staff_id_idx ON lead_interactions (staff_id);
CREATE INDEX lead_program_program_id_idx ON lead_program (program_id);
CREATE INDEX lead_program_lead_id_idx ON lead_program (lead_id);
CREATE INDEX leave_rules_leave_id_idx ON leave_rules (leave_id);
CREATE INDEX leave_staff_applications_leave_id_idx ON leave_staff_applications (leave_id);
CREATE INDEX leave_staff_applications_staff_id_idx ON leave_staff_applications (staff_id);
CREATE INDEX leave_staff_applications_alternate_idx ON leave_staff_applications (alternate);
CREATE INDEX leave_staff_entitlements_leave_id_idx ON leave_staff_entitlements (leave_id);
CREATE INDEX leave_staff_entitlements_staff_id_idx ON leave_staff_entitlements (staff_id);
CREATE INDEX nba_programs_nba_id_idx ON nba_programs (nba_id);
CREATE INDEX nba_programs_program_id_idx ON nba_programs (program_id);
CREATE INDEX notices_user_id_idx ON notices (user_id);
CREATE INDEX notifications_user_id_idx ON notifications (user_id);
CREATE INDEX ntcpayscale_staff_staff_id_idx ON ntcpayscale_staff (staff_id);
CREATE INDEX ntcpayscale_staff_ntcpayscale_id_idx ON ntcpayscale_staff (ntcpayscale_id);
CREATE INDEX ntissue_timelines_student_issue_id_idx ON ntissue_timelines (student_issue_id);
CREATE INDEX ntissue_timelines_status_updated_by_idx ON ntissue_timelines (status_updated_by);
CREATE INDEX ntpayscale_staff_staff_id_idx ON ntpayscale_staff (staff_id);
CREATE INDEX ntpayscale_staff_ntpayscale_id_idx ON ntpayscale_staff (ntpayscale_id);
CREATE INDEX patents_staff_id_idx ON patents (staff_id);
CREATE INDEX personal_access_tokens_tokenable_idx ON personal_access_tokens (tokenable_type, tokenable_id);
CREATE INDEX paas_staff_id_idx ON professional_activity_attendee_staff (staff_id);
CREATE INDEX paas_paa_id_idx ON professional_activity_attendee_staff (professional_activity_attendee_id);
CREATE INDEX programs_department_id_idx ON programs (department_id);
CREATE INDEX publications_staff_id_idx ON publications (staff_id);
CREATE INDEX qualification_staff_qualification_id_idx ON qualification_staff (qualification_id);
CREATE INDEX qualification_staff_staff_id_idx ON qualification_staff (staff_id);
CREATE INDEX reviewer_editors_staff_id_idx ON reviewer_editors (staff_id);
CREATE INDEX staff_castecategory_id_idx ON staff (castecategory_id);
CREATE INDEX staff_religion_id_idx ON staff (religion_id);
CREATE INDEX staff_user_id_idx ON staff (user_id);
CREATE INDEX stafflics_staff_id_idx ON stafflics (staff_id);
CREATE INDEX stafflic_transactions_stafflic_id_idx ON stafflic_transactions (stafflic_id);
CREATE INDEX staffremunerationheads_staff_id_idx ON staffremunerationheads (staff_id);
CREATE INDEX staffremunerationheads_remunerationhead_id_idx ON staffremunerationheads (remunerationhead_id);
CREATE INDEX staff_form16s_staff_id_idx ON staff_form16s (staff_id);
CREATE INDEX staff_taxregime_staff_id_idx ON staff_taxregime (staff_id);
CREATE INDEX staff_taxregime_tax_heads_id_idx ON staff_taxregime (tax_heads_id);
CREATE INDEX staff_tds_staff_id_idx ON staff_tds (staff_id);
CREATE INDEX staff_tds_staffsalary_id_idx ON staff_tds (staffsalary_id);
CREATE INDEX staff_tds_staff_taxregime_id_idx ON staff_tds (staff_taxregime_id);
CREATE INDEX staff_teaching_payscale_staff_id_idx ON staff_teaching_payscale (staff_id);
CREATE INDEX staff_teaching_payscale_teaching_payscale_id_idx ON staff_teaching_payscale (teaching_payscale_id);
CREATE INDEX stationary_indent_and_grants_stationary_id_idx ON stationary_indent_and_grants (stationary_id);
CREATE INDEX stationary_indent_and_grants_dept_indent_id_idx ON stationary_indent_and_grants (dept_stationary_indent_id);
CREATE INDEX studentinternships_spoc_id_idx ON studentinternships (spoc_id);
CREATE INDEX studentinternships_industry_id_idx ON studentinternships (industry_id);
CREATE INDEX students_staff_id_idx ON students (staff_id);
CREATE INDEX student_studentinternship_student_id_idx ON student_studentinternship (student_id);
CREATE INDEX student_studentinternship_studentinternship_id_idx ON student_studentinternship (studentinternship_id);
CREATE INDEX student_studentinternship_department_id_idx ON student_studentinternship (department_id);
CREATE INDEX student_studentinternship_staff_id_idx ON student_studentinternship (staff_id);
CREATE INDEX tax_slabs_regime_id_idx ON tax_slabs (regime_id);
CREATE INDEX teaching_payscales_designations_id_idx ON teaching_payscales (designations_id);
CREATE INDEX tenders_user_id_idx ON tenders (user_id);
CREATE INDEX tenders_document_idx ON tenders (document);
CREATE INDEX tender_configs_tender_id_idx ON tender_configs (tender_id);
CREATE INDEX tender_config_vendors_tender_configs_id_idx ON tender_config_vendors (tender_configs_id);
CREATE INDEX tender_config_vendors_t_vendor_id_idx ON tender_config_vendors (t_vendor_id);
CREATE INDEX tender_departments_tender_id_idx ON tender_departments (tender_id);
CREATE INDEX tender_departments_department_id_idx ON tender_departments (department_id);
CREATE INDEX tender_quote_otp_tender_id_idx ON tender_quote_otp (tender_id);
CREATE INDEX tender_quote_otp_t_vendor_id_idx ON tender_quote_otp (t_vendor_id);
CREATE INDEX tender_t_vendor_tender_id_idx ON tender_t_vendor (tender_id);
CREATE INDEX tender_t_vendor_t_vendor_id_idx ON tender_t_vendor (t_vendor_id);
CREATE INDEX tickets_user_id_idx ON tickets (user_id);

ALTER TABLE annual_increments ADD CONSTRAINT fk_ai_staff_id FOREIGN KEY (staff_id) REFERENCES staff(id);
ALTER TABLE association_staff ADD CONSTRAINT association_staff_associations_id_foreign FOREIGN KEY (association_id) REFERENCES associations(id) ON DELETE CASCADE;
ALTER TABLE association_staff ADD CONSTRAINT association_staff_staff_id_foreign FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;
ALTER TABLE autonomous_allowances ADD CONSTRAINT autonomous_allowances_department_id_foreign FOREIGN KEY (department_id) REFERENCES departments(id);
ALTER TABLE autonomous_allowances ADD CONSTRAINT autonomous_allowances_staff_id_foreign FOREIGN KEY (staff_id) REFERENCES staff(id);
ALTER TABLE book_publications ADD CONSTRAINT book_publications_staff_id_foreign FOREIGN KEY (staff_id) REFERENCES staff(id);
ALTER TABLE castecategories ADD CONSTRAINT castecategories_religion_id_foreign FOREIGN KEY (religion_id) REFERENCES religions(id);
ALTER TABLE combine_leaves ADD CONSTRAINT combine_leave_combined_id_foreign FOREIGN KEY (combined_id) REFERENCES leaves(id);
ALTER TABLE combine_leaves ADD CONSTRAINT combine_leave_leave_id_foreign FOREIGN KEY (leave_id) REFERENCES leaves(id);
ALTER TABLE conferences_attendee_staff ADD CONSTRAINT conferences_attendee_staff_conferences_attendee_id_foreign FOREIGN KEY (conferences_attendee_id) REFERENCES conferences_attendees(id);
ALTER TABLE conferences_attendee_staff ADD CONSTRAINT conferences_attendee_staff_staff_id_foreign FOREIGN KEY (staff_id) REFERENCES staff(id);
ALTER TABLE conferences_conducted_staff ADD CONSTRAINT conferences_conducted_staff_conferences_conducted_id_foreign FOREIGN KEY (conferences_conducted_id) REFERENCES conferences_conducteds(id);
ALTER TABLE conferences_conducted_staff ADD CONSTRAINT conferences_conducted_staff_staff_id_foreign FOREIGN KEY (staff_id) REFERENCES staff(id);
ALTER TABLE consultancies ADD CONSTRAINT consultancies_staff_id_foreign FOREIGN KEY (staff_id) REFERENCES staff(id);
ALTER TABLE daywise__leaves ADD CONSTRAINT fk_leave_staff_application_id FOREIGN KEY (leave_staff_applications_id) REFERENCES leave_staff_applications(id) ON DELETE CASCADE;
ALTER TABLE departments ADD CONSTRAINT fk_departments_user_id FOREIGN KEY (hod_user_id) REFERENCES users(id);
ALTER TABLE department_domains ADD CONSTRAINT department_domains_department_id_foreign FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE;
ALTER TABLE dept_stationary_indents ADD CONSTRAINT fk_department_id FOREIGN KEY (department_id) REFERENCES departments(id);
ALTER TABLE fastrack_courses ADD CONSTRAINT fk_instance_id FOREIGN KEY (ft_instance_id) REFERENCES fastrack_instances(id) ON DELETE CASCADE;
ALTER TABLE fastrack_courses ADD CONSTRAINT fastrack_courses_department_id_foreign FOREIGN KEY (department_id) REFERENCES departments(id);
ALTER TABLE fastrack_courses ADD CONSTRAINT foreign_ft_course_type_id FOREIGN KEY (ft_course_type_id) REFERENCES ftcourses(id);
ALTER TABLE fastrack_expenses ADD CONSTRAINT ft_expense_master_id FOREIGN KEY (ft_expense_master_id) REFERENCES fastrack_expenses_master(id);
ALTER TABLE fastrack_instances ADD CONSTRAINT fastrack_instances_scheme_id_foreign FOREIGN KEY (scheme_id) REFERENCES schemes(id);
ALTER TABLE fastrack_instance_program ADD CONSTRAINT fastrack_instance_programs_fastrack_instance_id_foreign FOREIGN KEY (fastrack_instance_id) REFERENCES fastrack_instances(id) ON DELETE CASCADE;
ALTER TABLE fastrack_instance_program ADD CONSTRAINT fastrack_instance_programs_program_id_foreign FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE;
ALTER TABLE fastrack_staffs ADD CONSTRAINT fastrack_staffs_course_id_foreign FOREIGN KEY (course_id) REFERENCES fastrack_courses(id) ON DELETE CASCADE;
ALTER TABLE fastrack_staffs ADD CONSTRAINT fastrack_staffs_staff_id_foreign FOREIGN KEY (staff_id) REFERENCES staff(id);
ALTER TABLE institution_staff ADD CONSTRAINT institution_staff_institution_id_foreign FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE;
ALTER TABLE institution_staff ADD CONSTRAINT institution_staff_staff_id_foreign FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE;
ALTER TABLE lead_interactions ADD CONSTRAINT lead_interactions_lead_id_foreign FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE lead_interactions ADD CONSTRAINT lead_interactions_user_id_foreign FOREIGN KEY (staff_id) REFERENCES staff(id);
ALTER TABLE lead_program ADD CONSTRAINT lead_program_lead_id_foreign FOREIGN KEY (lead_id) REFERENCES leads(id);
ALTER TABLE lead_program ADD CONSTRAINT lead_program_program_id_foreign FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE;
ALTER TABLE leave_rules ADD CONSTRAINT fk_leave_rule_leave_id FOREIGN KEY (leave_id) REFERENCES leaves(id) ON DELETE CASCADE;
ALTER TABLE staffremunerationheads ADD CONSTRAINT fk_staff_id FOREIGN KEY (staff_id) REFERENCES staff(id);
ALTER TABLE staffremunerationheads ADD CONSTRAINT fk_remunerationhead_id FOREIGN KEY (remunerationhead_id) REFERENCES remunerationheads(id);
ALTER TABLE staff_tds ADD CONSTRAINT staff_tds_staff_id_foreign FOREIGN KEY (staff_id) REFERENCES staff(id);
ALTER TABLE staff_tds ADD CONSTRAINT staff_tds_staff_taxregime_id_foreign FOREIGN KEY (staff_taxregime_id) REFERENCES staff_taxregime(id);
ALTER TABLE staff_tds ADD CONSTRAINT staff_tds_staffsalary_id_foreign FOREIGN KEY (staffsalary_id) REFERENCES staffsalaries(id);
ALTER TABLE stationary_indent_and_grants ADD CONSTRAINT fk_dept_stationary_indent_id FOREIGN KEY (dept_stationary_indent_id) REFERENCES dept_stationary_indents(id);
ALTER TABLE stationary_indent_and_grants ADD CONSTRAINT fk_stationary_id_foreign FOREIGN KEY (stationary_id) REFERENCES stationaries(id);
ALTER TABLE tenders ADD CONSTRAINT tenders_user_id_foreign FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE tender_configs ADD CONSTRAINT fk_tender_configs_tender_id FOREIGN KEY (tender_id) REFERENCES tenders(id) ON DELETE CASCADE;
ALTER TABLE tender_config_vendors ADD CONSTRAINT fk_tender_config_id FOREIGN KEY (tender_configs_id) REFERENCES tender_configs(id);
ALTER TABLE tender_config_vendors ADD CONSTRAINT foreign_t_vendor_id FOREIGN KEY (t_vendor_id) REFERENCES t_vendors(id);
ALTER TABLE tender_departments ADD CONSTRAINT tender_departments_department_id_foreign FOREIGN KEY (department_id) REFERENCES departments(id);
ALTER TABLE tender_departments ADD CONSTRAINT tender_departments_tender_id_foreign FOREIGN KEY (tender_id) REFERENCES tenders(id);
ALTER TABLE tender_quote_otp ADD CONSTRAINT tender_quote_otp_t_vendor_id_foreign FOREIGN KEY (t_vendor_id) REFERENCES t_vendors(id);
ALTER TABLE tender_quote_otp ADD CONSTRAINT tender_quote_otp_tender_id_foreign FOREIGN KEY (tender_id) REFERENCES tenders(id);
ALTER TABLE tender_t_vendor ADD CONSTRAINT fk_t_vendor_id FOREIGN KEY (t_vendor_id) REFERENCES t_vendors(id);
ALTER TABLE tender_t_vendor ADD CONSTRAINT fk_tender_id FOREIGN KEY (tender_id) REFERENCES tenders(id);