const { pool } = require('../config/db');

const normalizeDate = (value) => {
  if (value === undefined || value === null) return null;
  if (typeof value === 'string' && value.trim() === '') return null;
  return value;
};

const normalizeInteger = (value) => {
  if (value === undefined || value === null) return null;
  if (typeof value === 'string' && value.trim() === '') return null;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? Math.trunc(parsed) : null;
};

const LeaveRules = {
  async getAll(leave_id) {
    const result = await pool.query('SELECT * FROM leave_rules WHERE leave_id = $1 ORDER BY id DESC', [leave_id]);
    return result.rows;
  },
  async getById(id) {
    const result = await pool.query('SELECT * FROM leave_rules WHERE id = $1', [id]);
    return result.rows[0];
  },
  async create(data) {
    // Self-heal sequence drift to avoid duplicate key errors on autogenerated IDs.
    await pool.query(`
      SELECT setval(
        pg_get_serial_sequence('leave_rules', 'id'),
        COALESCE((SELECT MAX(id) FROM leave_rules), 1),
        true
      )
    `);

    const q = `INSERT INTO leave_rules (leave_id, carry_forwardable, cf_gcr, cf_wef, cf_closing_date, cf_closing_gcr, max_cf, entitlement_post_max_cf, encashable, enc_gcr, enc_wef, enc_closing_date, enc_closing_gcr, max_enc, gap, gap_gcr, gap_wef, gap_closing_date, gap_closing_gcr, min_gap, max_time_allowed, period, prior_intimation_days, status, created_at, updated_at)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,NOW(),NOW()) RETURNING *`;
    const cfWef = normalizeDate(data.cf_wef);
    const cfClosingDate = normalizeDate(data.cf_closing_date);
    const encWef = normalizeDate(data.enc_wef);
    const encClosingDate = normalizeDate(data.enc_closing_date);
    const gapWef = normalizeDate(data.gap_wef);
    const gapClosingDate = normalizeDate(data.gap_closing_date);
    const leaveId = normalizeInteger(data.leave_id);
    const maxCf = normalizeInteger(data.max_cf);
    const entitlementPostMaxCf = normalizeInteger(data.entitlement_post_max_cf);
    const maxEnc = normalizeInteger(data.max_enc);
    const minGap = normalizeInteger(data.min_gap);
    const maxTimeAllowed = normalizeInteger(data.max_time_allowed);
    const priorIntimationDays = normalizeInteger(data.prior_intimation_days);
    const values = [
      leaveId,
      data.carry_forwardable,
      data.cf_gcr,
      cfWef,
      cfClosingDate,
      data.cf_closing_gcr,
      maxCf,
      entitlementPostMaxCf,
      data.encashable,
      data.enc_gcr,
      encWef,
      encClosingDate,
      data.enc_closing_gcr,
      maxEnc,
      data.gap,
      data.gap_gcr,
      gapWef,
      gapClosingDate,
      data.gap_closing_gcr,
      minGap,
      maxTimeAllowed,
      data.period,
      priorIntimationDays,
      data.status
    ];
    const result = await pool.query(q, values);
    return result.rows[0];
  },
  async update(id, data) {
    const q = `UPDATE leave_rules SET leave_id=$1, carry_forwardable=$2, cf_gcr=$3, cf_wef=$4, cf_closing_date=$5, cf_closing_gcr=$6, max_cf=$7, entitlement_post_max_cf=$8, encashable=$9, enc_gcr=$10, enc_wef=$11, enc_closing_date=$12, enc_closing_gcr=$13, max_enc=$14, gap=$15, gap_gcr=$16, gap_wef=$17, gap_closing_date=$18, gap_closing_gcr=$19, min_gap=$20, max_time_allowed=$21, period=$22, prior_intimation_days=$23, status=$24, updated_at=NOW() WHERE id=$25 RETURNING *`;
    const cfWef = normalizeDate(data.cf_wef);
    const cfClosingDate = normalizeDate(data.cf_closing_date);
    const encWef = normalizeDate(data.enc_wef);
    const encClosingDate = normalizeDate(data.enc_closing_date);
    const gapWef = normalizeDate(data.gap_wef);
    const gapClosingDate = normalizeDate(data.gap_closing_date);
    const leaveId = normalizeInteger(data.leave_id);
    const maxCf = normalizeInteger(data.max_cf);
    const entitlementPostMaxCf = normalizeInteger(data.entitlement_post_max_cf);
    const maxEnc = normalizeInteger(data.max_enc);
    const minGap = normalizeInteger(data.min_gap);
    const maxTimeAllowed = normalizeInteger(data.max_time_allowed);
    const priorIntimationDays = normalizeInteger(data.prior_intimation_days);
    const values = [
      leaveId,
      data.carry_forwardable,
      data.cf_gcr,
      cfWef,
      cfClosingDate,
      data.cf_closing_gcr,
      maxCf,
      entitlementPostMaxCf,
      data.encashable,
      data.enc_gcr,
      encWef,
      encClosingDate,
      data.enc_closing_gcr,
      maxEnc,
      data.gap,
      data.gap_gcr,
      gapWef,
      gapClosingDate,
      data.gap_closing_gcr,
      minGap,
      maxTimeAllowed,
      data.period,
      priorIntimationDays,
      data.status,
      id
    ];
    const result = await pool.query(q, values);
    return result.rows[0];
  },
  async delete(id) {
    await pool.query('DELETE FROM leave_rules WHERE id = $1', [id]);
    return { id };
  }
};

module.exports = LeaveRules;
